-- Custom T4 heroes, Armada (denysfast/bar-game), v19: the ten heroes of the altar armt4gant and their summons.
-- Design: doc/v19-heroes/roster_arm.md. Built from T3 gantry / scavenger units, see gamedata/custom_t4.lua; level-1
-- health, DPS and speed come from T4.heroBalance (gamedata/custom_t4.lua), abilities from
-- luarules/configs/heroes/arm.lua + luarules/heroes/armt4*.lua (hero gadget luarules/gadgets/unit_t4_heroes.lua).
-- Models: objects3d/Units/T4/<name>.s3o, generated by tools/t4/build_models.py (scale factors below must match).
-- Extra weapondefs (the third argument of T4.hero) become <hero>_<key>: the ability modules spawn them (api.fire),
-- they are never in a hero's weapon list. Never a StarburstLauncher among them (v15.1 savegame crash).
local T4 = VFS.Include("gamedata/custom_t4.lua")

local units = {}

-- Colossus Forge: the Armada hero altar (Experimental Gantry model x1.5)
units.armt4gant = T4.foundry(T4.base("units/ArmBuildings/LandFactories/armshltx.lua", "armshltx"), {
	name = "armt4gant",
	value = 8, -- v15: the altar costs 2x (metal, energy, build time); health and build power stay
	scale = 1.5,
	workertime = 12,
	buildoptions = {
		"armt4zeus", "armt4atlas", "armt4peewee", "armt4aegis", "armt4prowler",
		"armt4ratte", "armt4recluse", "armt4olympus", "armt4starlight", "armt4hive",
	},
})

local function damageAll(wd, dmg)
	wd.damage = { default = dmg, vtol = dmg, commanders = dmg }
	return wd
end

-- a plain ability shell (hero_*): no engine damage worth mentioning - api.fire with opts.dmg deals the ability's
local function abilityShell(o)
	local w = T4.shellWeapon(o)
	w.customparams.t4_ability = 1
	w.interceptedbyshieldtype = 0
	return w
end

------------------------------------------------------------------------------------------------ 1. Thor
-- armt4zeus: Thor, the Stormbreaker (armthor x1.8). Electric tank: Thunder Coil chains, EMP missile active,
-- Electro-Devour, Rage Mode. The stock EMP starburst stays in the weapon list (the COB script aims it) but never
-- fires: no stockpile, the module disables it; a2 fires the MissileLauncher copy hero_empmissile (config).
local zeus = T4.derive(T4.base("units/ArmGantry/armthor.lua", "armthor"), {
	name = "armt4zeus",
	value = 9.6,
	health = 6,
	damage = 4.4,
	range = 1.8,
	aoe = 2.0,
	scale = 1.8,
	speed = 0.8,
	footprint = 9,
	movementclass = "T4TANK9",
	weapons = {
		empmissile = { range = 1.0, stockpile = false, stockpiletime = nil, metalpershot = 0, energypershot = 0 },
	},
})
zeus.weapondefs.empmissile.customparams.stockpilelimit = nil
-- armthor.bos + SetTurretTurnMult (Rage Mode turns the turret faster: buff turretTurn), scripts/Units/armt4zeus.bos
zeus.script = "Units/armt4zeus.cob"
units.armt4zeus = T4.hero(zeus, 2.2)

------------------------------------------------------------------------------------------------ 2. Atlas
-- armt4atlas: Atlas, the Bulwark (Bantha x2). Doom Lens, Bulwark Protocol, Seismic Charge, Doomsday Lance.
local atlas = T4.derive(T4.base("units/ArmGantry/armbanth.lua", "armbanth"), {
	name = "armt4atlas",
	value = 8.8,
	health = 7.2,
	damage = 7.2,
	range = 1.8,
	aoe = 1.8,
	scale = 2.0,
	speed = 0.8,
	footprint = 8,
	movementclass = "T4BOT8",
})
units.armt4atlas = T4.hero(atlas, 2.5)

------------------------------------------------------------------------------------------------ 3. Peewee Prime
-- armt4peewee: Peewee Prime, the Vanguard of the Swarm (scavenger armpwt4 x1.8). Rapid plasma guns; Pack Leader,
-- Jump Jets, Bullet Hell, Overrun.
local peewee = T4.derive(T4.base("units/Scavengers/Bots/armpwt4.lua", "armpwt4"), {
	name = "armt4peewee",
	value = 10,
	health = 8,
	damage = 6,
	range = 1.8,
	aoe = 2.0,
	scale = 1.8,
	speed = 0.75,
	footprint = 8,
	movementclass = "T4BOT8",
	turn = 0.6,
})
units.armt4peewee = T4.hero(peewee, 2.2)

------------------------------------------------------------------------------------------------ 4. Razor
-- armt4aegis: Razor, the Phantom (Razorback x2). Laser assassin: Phantom Cloak, Deflector Shell (a Lua absorb
-- pool - the v18 shield weapon is gone), Overcharge, Razor Swarm (real drone units, armt4aegis_drone).
local aegis = T4.derive(T4.base("units/ArmGantry/armraz.lua", "armraz"), {
	name = "armt4aegis",
	value = 11.2,
	health = 3.2,
	damage = 4.8,
	range = 1.6,
	aoe = 1.6,
	scale = 2.0,
	speed = 0.85,
	footprint = 8,
	movementclass = "T4BOT8",
	accel = 0.9,
	turn = 0.8,
})
units.armt4aegis = T4.hero(aegis, 2.5)

-- Razor Swarm drone (armdrone x1.6): red beam laser; damage per rank and level through the hero module
local razorDrone = T4.derive(T4.base("units/ArmAircraft/armdrone.lua", "armdrone"), {
	name = "armt4aegis_drone",
	value = 1,
	health = 1,
	damage = 1,
	scale = 1.6,
	footprint = 2,
	speed = 0.6,
	accel = 1.5,
	turn = 1,
	sight = 1.4,
	explodeas = "smallExplosionGeneric",
	selfdestructas = "smallExplosionGenericSelfd",
	overrides = {
		health = 6000,
		metalcost = 400,
		energycost = 4000,
		buildtime = 4000,
		cruisealtitude = 110,
		weapondefs = {
			hero_dronelaser = {
				areaofeffect = 12,
				avoidfeature = false,
				beamtime = 0.12,
				corethickness = 0.3,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:laserhit-small-red",
				impulsefactor = 0,
				laserflaresize = 6,
				name = "Razor drone laser",
				noselfdamage = true,
				range = 600,
				reloadtime = 0.5,
				rgbcolor = "1 0.12 0.08",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "lasrfir1",
				soundtrigger = 1,
				thickness = 2.6,
				tolerance = 10000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 1500,
				collidefriendly = false,
				damage = { default = 350, vtol = 100 },
			},
		},
		weapons = { { def = "HERO_DRONELASER", onlytargetcategory = "SURFACE", badtargetcategory = "VTOL" } },
		customparams = { t4_summon = 1, techlevel = 3 },
	},
})
razorDrone.featuredefs = nil
razorDrone.buildpic = "ARMKAM.DDS"
units.armt4aegis_drone = razorDrone

------------------------------------------------------------------------------------------------ 5. Prowler
-- armt4prowler: Prowler, the Riptide (armprowl x2.6, amphibious). Twin gauss + tandem missiles (ground too);
-- Tandem Strike, Harpoon, Riptide Fog, Apex Predator.
local prowler = T4.derive(T4.base("units/ArmGantry/armprowl.lua", "armprowl"), {
	name = "armt4prowler",
	value = 9,
	health = 8,
	damage = 8,
	range = 1.9,
	aoe = 2.0,
	scale = 2.6,
	speed = 0.6,
	footprint = 8,
	movementclass = "T4ATANK8",
})
damageAll(prowler.weapondefs.armamph_missile, 400)
prowler.weapondefs.armamph_missile.name = "Tandem missiles"
prowler.weapons[2].onlytargetcategory = "SURFACE VTOL"
prowler.weapons[2].badtargetcategory = nil
units.armt4prowler = T4.hero(prowler, 2.2)

------------------------------------------------------------------------------------------------ 6. Ratte
-- armt4ratte: Ratte, the Landship (scavenger armrattet4 x1.5). Five-shell main battery; Overpressure, Creeping
-- Barrage, Landship Plating, Main Gun.
local ratte = T4.derive(T4.base("units/Scavengers/Vehicles/armrattet4.lua", "armrattet4"), {
	name = "armt4ratte",
	value = 4,
	health = 6,
	damage = 3,
	range = 1.3,
	aoe = 1.2,
	scale = 1.5,
	speed = 1,
	footprint = 9,
	movementclass = "T4TANK9",
	turn = 0.7,
})
units.armt4ratte = T4.hero(ratte, 2.0, {
	-- a2 Creeping Barrage: one high-arc shell of the walk (damage from the ability)
	hero_barrage = abilityShell({ name = "Creeping barrage shell", aoe = 220, damage = 1, size = 8, velocity = 900,
		gravity = 0.35, rgb = "1 0.7 0.3", ceg = "custom:genericshellexplosion-large-aoe", soundhit = "xplonuk2xs",
		soundstart = "shotgunbig", range = 3000 }),
	-- ult Main Gun: one slow super shell on a high arc
	hero_supershell = abilityShell({ name = "Main gun super shell", aoe = 500, damage = 1, size = 22, velocity = 1100,
		gravity = 0.3, rgb = "1 0.85 0.55", ceg = "custom:genericshellexplosion-huge", soundhit = "xplomed4",
		soundstart = "xplolrg1", range = 5000 }),
})

------------------------------------------------------------------------------------------------ 7. Recluse
-- armt4recluse: Recluse Matriarch (scavenger armsptkt4 x1.6, all-terrain). Parabolic rocket salvos; Web Rockets,
-- Web Field, Cocoon, Rocket Monsoon.
local recluse = T4.derive(T4.base("units/Scavengers/Bots/armsptkt4.lua", "armsptkt4"), {
	name = "armt4recluse",
	value = 9,
	health = 9,
	damage = 6,
	range = 1.8,
	aoe = 1.6,
	scale = 1.6,
	speed = 1,
	footprint = 9,
	movementclass = "T4TBOT9",
	weapons = {
		adv_rocket = { reloadtime = 6 },
	},
})
units.armt4recluse = T4.hero(recluse, 2.2, {
	-- a2 Web Field: the canister (0 damage, the field is the ability)
	hero_webcanister = abilityShell({ name = "Web canister", aoe = 60, damage = 1, size = 6, velocity = 900, gravity = 0.4,
		rgb = "0.85 1 0.85", ceg = "custom:genericshellexplosion-medium-bomb", soundhit = "xplosml3", soundstart = "cannon2",
		range = 2000 }),
	-- ult Rocket Monsoon: rockets falling from above (no trajectory height: a spawned one would lose its target)
	hero_monsoon = (function()
		local w = T4.missileWeapon({ name = "Monsoon rocket", damage = 1, aoe = 160, model = "catapultmissile.s3o",
			ceg = "custom:genericshellexplosion-catapult", cegtag = "missiletrailsmall", soundhit = "rockhit",
			soundstart = "rocksalvo", velocity = 900, range = 4000, turnrate = 30000 })
		w.smoketrail = false
		w.customparams.t4_ability = 1
		return w
	end)(),
})

-- Cocoon hatchling (armspid x1.4): an EMP spider for 20 s
local spiderling = T4.derive(T4.base("units/ArmBots/T2/armspid.lua", "armspid"), {
	name = "armt4recluse_spiderling",
	value = 4,
	health = 4,
	damage = 4,
	range = 1.3,
	aoe = 1,
	scale = 1.4,
	speed = 1,
	footprint = 3,
	movementclass = "TBOT3",
	explodeas = "mediumExplosionGeneric",
	selfdestructas = "mediumExplosionGenericSelfd",
	overrides = { customparams = { t4_summon = 1, techlevel = 3 } },
})
spiderling.featuredefs = nil
spiderling.buildoptions = nil
units.armt4recluse_spiderling = spiderling

------------------------------------------------------------------------------------------------ 8. Olympus
-- armt4olympus: Olympus, the Thunderer (Vanguard x2.2): strategic artillery. Cluster Shells, Spotter Flare, Siege
-- Anchor, Ion Lance.
local olympus = T4.derive(T4.base("units/ArmGantry/armvang.lua", "armvang"), {
	name = "armt4olympus",
	value = 14.4,
	health = 6,
	damage = 11.2,
	range = 2.3, -- 3340 at level 1
	aoe = 2.5,
	scale = 2.2,
	speed = 0.75,
	sight = 1.8,
	footprint = 9,
	movementclass = "T4TBOT9",
	overrides = { radardistance = 3600 },
})
units.armt4olympus = T4.hero(olympus, 2.5, {
	-- a1 Cluster Shells: a bomblet of the split (damage from the ability)
	hero_bomblet = abilityShell({ name = "Cluster bomblet", aoe = 90, damage = 1, size = 3.5, velocity = 420, gravity = 0.5,
		rgb = "0.6 0.85 1", ceg = "custom:genericshellexplosion-medium", soundhit = "xplosml3", range = 800 }),
	-- a2 Spotter Flare
	hero_flare = abilityShell({ name = "Spotter flare", aoe = 20, damage = 1, size = 5, velocity = 1600, gravity = 0.25,
		rgb = "0.6 0.95 1", ceg = "custom:genericshellexplosion-small-lightning", soundhit = "xplosml3",
		soundstart = "cannhvy5", range = 9000 }),
})

------------------------------------------------------------------------------------------------ 9. Starlight
-- armt4starlight: Starlight, the Lance (armmanni x2.4): the tachyon sniper. Focusing Array, Prism Relay, Phase
-- Shift, Solar Lance.
local starlight = T4.derive(T4.base("units/ArmVehicles/T2/armmanni.lua", "armmanni"), {
	name = "armt4starlight",
	value = 10,
	health = 10,
	damage = 6,
	range = 2.2,
	aoe = 2,
	scale = 2.4,
	speed = 1,
	sight = 2.2,
	footprint = 9,
	movementclass = "T4TANK9",
	turn = 0.8,
})
units.armt4starlight = T4.hero(starlight, 2.2)

------------------------------------------------------------------------------------------------ 10. Hive Mother
-- armt4hive: Hive Mother (scavenger armdronecarryland x1.5): the drone carrier. Its stockpile drone launcher and
-- the carrier customparams are gone (unit_carrier_spawner must not run a second drone system): a point-defence
-- laser of its own; the drones are hero summons (Drone Bay, Mothership Protocol).
local hiveBase = T4.base("units/Scavengers/Vehicles/armdronecarryland.lua", "armdronecarryland")
hiveBase.weapondefs = {
	hero_pdlaser = {
		areaofeffect = 16,
		avoidfeature = false,
		beamtime = 0.15,
		corethickness = 0.3,
		craterareaofeffect = 0,
		craterboost = 0,
		cratermult = 0,
		edgeeffectiveness = 0.15,
		explosiongenerator = "custom:laserhit-medium-yellow",
		impulsefactor = 0,
		laserflaresize = 7,
		name = "Point-defence laser",
		noselfdamage = true,
		range = 900,
		reloadtime = 0.4,
		rgbcolor = "1 0.75 0.25",
		soundhitdry = "",
		soundhitwet = "sizzle",
		soundstart = "lasrhvy3",
		soundtrigger = 1,
		thickness = 3.2,
		tolerance = 10000,
		turret = true,
		weapontype = "BeamLaser",
		weaponvelocity = 1500,
		damage = { default = 600, vtol = 300 },
	},
}
hiveBase.weapons = { { def = "HERO_PDLASER", onlytargetcategory = "NOTSUB" } }
local hive = T4.derive(hiveBase, {
	name = "armt4hive",
	value = 9,
	health = 9,
	damage = 1,
	range = 1,
	aoe = 1,
	scale = 1.5,
	speed = 1,
	turn = 1,
	footprint = 9,
	movementclass = "T4TANK9",
})
for _, k in ipairs({ "inheritxpratemultiplier", "childreninheritxp", "parentsinheritxp" }) do
	hive.customparams[k] = nil
end
units.armt4hive = T4.hero(hive, 2.0, {
	-- a3 Kamikaze Run: only the blast (the diving drone is a unit; damage from the ability)
	hero_dronebomb = abilityShell({ name = "Kamikaze drone", aoe = 200, damage = 1, size = 4, velocity = 600,
		rgb = "1 0.6 0.2", ceg = "custom:genericshellexplosion-large", soundhit = "xplomed2", range = 2000 }),
})

-- Drone Bay drone (armdrone x1.8): amber beam; HP and damage grow with the hero (module: rank, level)
local hiveDrone = T4.derive(T4.base("units/ArmAircraft/armdrone.lua", "armdrone"), {
	name = "armt4hive_drone",
	value = 1,
	health = 1,
	damage = 1,
	scale = 1.8,
	footprint = 2,
	speed = 0.5,
	accel = 1.2,
	turn = 1,
	sight = 1.4,
	explodeas = "smallExplosionGeneric",
	selfdestructas = "smallExplosionGenericSelfd",
	overrides = {
		health = 5000,
		metalcost = 300,
		energycost = 3000,
		buildtime = 3000,
		cruisealtitude = 80,
		weapondefs = {
			hero_dronelaser_hive = {
				areaofeffect = 12,
				avoidfeature = false,
				beamtime = 0.1,
				corethickness = 0.3,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:laserhit-small-yellow",
				impulsefactor = 0,
				laserflaresize = 5,
				name = "Hive drone laser",
				noselfdamage = true,
				range = 450,
				reloadtime = 0.25,
				rgbcolor = "1 0.7 0.2",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "lasrfir1",
				soundtrigger = 1,
				thickness = 2.2,
				tolerance = 10000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 1500,
				damage = { default = 145, vtol = 50 },
			},
		},
		weapons = { { def = "HERO_DRONELASER_HIVE", onlytargetcategory = "SURFACE", badtargetcategory = "VTOL" } },
		customparams = { t4_summon = 1, techlevel = 3 },
	},
})
hiveDrone.featuredefs = nil
units.armt4hive_drone = hiveDrone

-- Mothership guardian (armdroneold x2.5): a missile gunship, 1500 DPS, 20k HP
local guardian = T4.derive(T4.base("units/ArmAircraft/armdroneold.lua", "armdroneold"), {
	name = "armt4hive_guardian",
	value = 1,
	health = 1,
	damage = 1,
	scale = 2.5,
	footprint = 3,
	speed = 0.7,
	accel = 1,
	turn = 1,
	sight = 1.5,
	explodeas = "mediumExplosionGeneric",
	selfdestructas = "mediumExplosionGenericSelfd",
	overrides = {
		health = 20000,
		metalcost = 1500,
		energycost = 15000,
		buildtime = 15000,
		cruisealtitude = 140,
		weapondefs = {
			hero_guardmissile = {
				areaofeffect = 80,
				avoidfeature = false,
				burnblow = true,
				cegtag = "missiletrailsmall-simple",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:genericshellexplosion-medium",
				flighttime = 3,
				impulsefactor = 0.1,
				model = "cormissile.s3o",
				name = "Guardian missiles",
				noselfdamage = true,
				range = 700,
				reloadtime = 0.5,
				smoketrail = true,
				smokePeriod = 6,
				smoketime = 12,
				smokesize = 4,
				smokecolor = 0.7,
				soundhit = "xplosml2",
				soundhitwet = "splsmed",
				soundstart = "rocklit1",
				startvelocity = 300,
				texture1 = "null",
				texture2 = "smoketrailbar",
				tolerance = 9000,
				tracks = true,
				turnrate = 30000,
				turret = true,
				weaponacceleration = 300,
				weapontimer = 2,
				weapontype = "MissileLauncher",
				weaponvelocity = 900,
				collidefriendly = false,
				damage = { default = 750, vtol = 200 },
			},
		},
		weapons = { { def = "HERO_GUARDMISSILE", onlytargetcategory = "SURFACE", badtargetcategory = "VTOL" } },
		customparams = { t4_summon = 1, techlevel = 3 },
	},
})
guardian.featuredefs = nil
units.armt4hive_guardian = guardian

return units
