-- Custom T4 tier (denysfast/bar-game): builds T4 unitdefs from existing T2/T3 unitdefs.
-- Used from units/*/T4/*.lua via VFS.Include; lives outside units/ so the unitdef loader does not
-- try to load it as a unit. See CUSTOM.md, section "T4".
--
-- A T4 unit = the base unit's model scaled up (objects3d/Units/T4/<name>.s3o, generated by
-- tools/t4/build_models.py - the engine cannot scale models at runtime), its script, sounds and
-- weapons, with:
--   * cost, buildtime, health scaled by `value` (T4 is to T3 roughly what T3 is to T1)
--   * weapon damage scaled by `damage`, range by `range`, area of effect by `aoe`
--   * footprint / collision volume / movement class sized for the bigger model

local T4 = {}

local function deepcopy(v)
	if type(v) ~= "table" then
		return v
	end
	local out = {}
	for k, x in pairs(v) do
		out[k] = deepcopy(x)
	end
	return out
end
T4.deepcopy = deepcopy

local function scaleVec(str, mult)
	if type(str) ~= "string" then
		return str
	end
	local parts = {}
	for n in str:gmatch("%S+") do
		parts[#parts + 1] = string.format("%.1f", (tonumber(n) or 0) * mult)
	end
	return table.concat(parts, " ")
end
T4.scaleVec = scaleVec

local function mulField(t, key, mult)
	if t[key] then
		t[key] = t[key] * mult
	end
end

-- load one unitdef table from a unit file
function T4.base(path, name)
	local defs = VFS.Include(path)
	return deepcopy(defs[name])
end

-- scale one weapondef in place
-- opts: damage, range, aoe, velocity (default sqrt(range) so ballistic weapons still reach), size
function T4.scaleWeapon(wd, opts)
	local damage = opts.damage or 1
	local range = opts.range or 1
	if wd.damage then
		for armor, v in pairs(wd.damage) do
			wd.damage[armor] = v * damage
		end
	end
	if wd.range and wd.range > 0 then
		wd.range = wd.range * range
	end
	mulField(wd, "areaofeffect", opts.aoe or 1)
	mulField(wd, "craterareaofeffect", opts.aoe or 1)
	local vel = opts.velocity or math.sqrt(range)
	mulField(wd, "weaponvelocity", vel)
	mulField(wd, "startvelocity", vel)
	mulField(wd, "flighttime", range / vel)
	mulField(wd, "size", opts.size or 1)
	mulField(wd, "thickness", opts.size or 1)
	mulField(wd, "corethickness", opts.size or 1)
	mulField(wd, "camerashake", opts.aoe or 1)
	if wd.customparams and wd.customparams.overrange_distance then
		wd.customparams.overrange_distance = wd.customparams.overrange_distance * range
	end
	return wd
end

-- build a T4 unitdef
-- p = { value, health, damage, range, aoe, scale, speed, footprint, movementclass, metalcost,
--       weapons = { <key> = { damage=, range=, aoe=, velocity=, ... override fields } },
--       overrides = { field = value, customparams = {...} } }
function T4.derive(base, p)
	local ud = deepcopy(base)
	ud.objectname = "Units/T4/" .. p.name .. ".s3o"
	local value = p.value
	local scale = p.scale or 2

	ud.metalcost = p.metalcost or math.floor(ud.metalcost * value)
	ud.energycost = math.floor((ud.energycost or 0) * value)
	ud.buildtime = math.floor((ud.buildtime or 0) * value)
	ud.health = math.floor(ud.health * (p.health or value))
	ud.mass = ud.metalcost
	ud.speed = (ud.speed or 0) * (p.speed or 0.75)
	mulField(ud, "maxacc", p.accel or 0.6)
	mulField(ud, "maxdec", p.accel or 0.6)
	mulField(ud, "turnrate", p.turn or 0.55)
	mulField(ud, "turninplacespeedlimit", p.speed or 0.75)
	ud.sightdistance = math.floor((ud.sightdistance or 400) * (p.sight or 1.6))
	if ud.airsightdistance then
		ud.airsightdistance = math.floor(ud.airsightdistance * (p.sight or 1.6))
	end
	ud.footprintx = p.footprint
	ud.footprintz = p.footprint
	ud.movementclass = p.movementclass
	ud.maxslope = nil -- the movement class decides
	ud.maxwaterdepth = nil
	ud.collisionvolumescales = scaleVec(ud.collisionvolumescales, scale)
	ud.collisionvolumeoffsets = scaleVec(ud.collisionvolumeoffsets, scale)
	ud.cantbetransported = true
	ud.explodeas = p.explodeas or "korgExplosion"
	ud.selfdestructas = p.selfdestructas or "korgExplosionSelfd"
	ud.selfdestructcountdown = 10

	local cp = ud.customparams or {}
	ud.customparams = cp
	cp.techlevel = 4
	cp.t4_scale = scale
	cp.unitgroup = cp.unitgroup or "weapon"
	cp.subfolder = "T4"
	cp.rangexpscale = nil -- the stock weapon-1 range bonus would stack on the hero levels
	if cp.customrange then
		cp.customrange = cp.customrange * (p.range or 1)
	end

	-- wreck: the scaled wreck model, its metal follows the new cost
	if ud.featuredefs then
		for fname, fd in pairs(ud.featuredefs) do
			if fd.metal then
				fd.metal = math.floor(ud.metalcost * (fname == "dead" and 0.55 or 0.22))
			end
			if fname == "dead" then
				fd.object = "Units/T4/" .. p.name .. "_dead.s3o"
				fd.collisionvolumescales = scaleVec(fd.collisionvolumescales, scale)
				fd.collisionvolumeoffsets = scaleVec(fd.collisionvolumeoffsets, scale)
				if fd.footprintx then
					fd.footprintx = math.floor(fd.footprintx * scale + 0.5)
					fd.footprintz = math.floor((fd.footprintz or fd.footprintx) * scale + 0.5)
				end
				mulField(fd, "height", scale)
			end
			if fd.damage then
				fd.damage = math.floor(fd.damage * value)
			end
		end
	end

	-- weapons: global multipliers, then per-weapon overrides
	if ud.weapondefs then
		for key, wd in pairs(ud.weapondefs) do
			local w = p.weapons and p.weapons[key] or {}
			T4.scaleWeapon(wd, {
				damage = w.damage or p.damage or value,
				range = w.range or p.range or 1,
				aoe = w.aoe or p.aoe or 1.5,
				velocity = w.velocity,
				size = w.size or math.sqrt(scale),
			})
			for field, v in pairs(w) do
				if field ~= "damage" and field ~= "range" and field ~= "aoe" and field ~= "velocity" and field ~= "size" then
					wd[field] = deepcopy(v)
				end
			end
		end
	end

	if p.overrides then
		for field, v in pairs(p.overrides) do
			if field == "customparams" then
				for k, x in pairs(v) do
					cp[k] = x
				end
			else
				ud[field] = deepcopy(v)
			end
		end
	end
	return ud
end

------------------------------------------------------------------------------- heroes
-- Every T4 is a hero (luarules/configs/t4_heroes.lua, luarules/gadgets/unit_t4_heroes.lua): one per
-- team, levels, talents, revive. T4.hero finishes a derived unitdef:
--   * maxthisunit = 1, customparams.t4_hero
--   * every CEG reference of its weapons and unit script scaled up by `fx` (gamedata/custom_t4_fx.lua)
--   * p.weapons: extra weapondefs "hero_*" the gadget spawns (swapped projectiles, meteors, novas);
--     they are not in the weapons list, the engine still registers them as <unit>_hero_*

local FX = VFS.Include("gamedata/custom_t4_fx.lua")
T4.FX = FX

local function scaleCegRefs(wd, fx)
	if wd.explosiongenerator then
		wd.explosiongenerator = FX.ref(wd.explosiongenerator, fx)
	end
	if wd.cegtag then
		wd.cegtag = FX.ref(wd.cegtag, fx)
	end
	if wd.customparams and wd.customparams.water_splash_ceg then
		wd.customparams.water_splash_ceg = FX.ref(wd.customparams.water_splash_ceg, fx)
	end
end

-- the hero design data (luarules/configs/t4_heroes.lua), loaded once; nil when it cannot load here
local heroH
local function heroConfig()
	if heroH == nil then
		local ok, res = pcall(VFS.Include, "luarules/configs/t4_heroes.lua")
		heroH = ok and res or false
		if not ok and Spring and Spring.Echo then
			Spring.Echo("[custom_t4] hero config not loaded: " .. tostring(res))
		end
	end
	return heroH or nil
end

-- v17: every T4 hero costs the same and is sized by its role (the cheap ones were paper, the expensive ones
-- tanks). T4.hero applies it first: cost, health, speed, and one damage
-- multiplier over its real weapons so their army DPS (damage x salvo x projectiles / reload x T4.armyFactor of the
-- blast; not paralyzers, aiming dummies or melee kicks under 150 range) meets `dps`. Level 1 values. v19: the
-- single-target DPS of a splash hero is lower than `dps` (Olympus ~2000, Starfall ~3200, Armageddon ~5100).
T4.HERO_COST = { metal = 100000, energy = 2000000, buildtime = 2500000 }
T4.heroBalance = {
	--                  health     dps      speed (elmos/s)
	armt4atlas      = { hp = 420000, dps = 11000, speed = 36 }, -- front: assault anchor
	armt4zeus       = { hp = 400000, dps = 10000, speed = 40 }, -- front: lightning + EMP (not counted)
	cort4colossus   = { hp = 440000, dps = 10000, speed = 34 }, -- front: initiator, crowd control
	cort4bastion    = { hp = 520000, dps = 8500, speed = 30 },  -- front: Juggernaut, killer tank that gets up again
	cort4hellwalker = { hp = 400000, dps = 12000, speed = 50 }, -- front: flame brawler (800 range)
	legt4tempest    = { hp = 380000, dps = 12000, speed = 58 }, -- front: melee assault (670 range)
	legt4keres      = { hp = 480000, dps = 9500, speed = 40 },  -- front: anti-swarm brawler (v19 Legion)
	legt4mukade     = { hp = 360000, dps = 10000, speed = 52 }, -- front: burrowing assassin (v19 Legion)
	armt4aegis      = { hp = 320000, dps = 8000, speed = 48 },  -- center: shield bearer (plus its deflector)
	legt4helios     = { hp = 340000, dps = 10500, speed = 34 }, -- center: heat / support
	legt4longinus   = { hp = 300000, dps = 11000, speed = 45 }, -- center: titan hunter
	legt4charybdis  = { hp = 320000, dps = 4850, speed = 60 },  -- center: crowd control hover (v19 Legion): real ~9000, the
	                                                             -- sweepfire heat ray counts once per 3 s (units/Legion/T4)
	legt4apollyon   = { hp = 440000, dps = 10500, speed = 30 }, -- center: suppression / siege (v19 Legion)
	armt4olympus    = { hp = 220000, dps = 8000, speed = 30, alt = { shocker_high = true } }, -- back: artillery 3300+ (high/low arc: one fires)
	cort4armageddon = { hp = 220000, dps = 8000, speed = 34 },  -- back: rocket artillery 2700+
	legt4starfall   = { hp = 220000, dps = 6500, speed = 26 },  -- back: orbital artillery ~7000
	legt4myrmidon   = { hp = 260000, dps = 6500, speed = 32, alt = { plasma_high = true } }, -- back: hive mother (+drones; v19 Legion)
	legt4medusa     = { hp = 230000, dps = 7500, speed = 34 },  -- back: petrify rocket artillery (v19 Legion)
	-- v19 Cortex roster (doc/v19-heroes/roster_cor.md)
	cort4vesuvius   = { hp = 380000, dps = 10000, speed = 34 }, -- center: twin-barrel siege tank
	cort4printer    = { hp = 300000, dps = 5000, speed = 42 },  -- center: drone carrier (+ drones)
	cort4commando   = { hp = 240000, dps = 11000, speed = 70 }, -- front: cloaked assassin (+ EMP, not counted)
	cort4deadeye    = { hp = 220000, dps = 9000, speed = 30 },  -- back: sniper 1870
	cort4karganeth  = { hp = 340000, dps = 10000, speed = 40 }, -- center: missiles + AA (vtol only, not counted)
	cort4cataphract = { hp = 300000, dps = 10000, speed = 64, alt = { depthcharge = true } }, -- front: hover lancer
}
-- Armada (v19, doc/v19-heroes/roster_arm.md; content-arm owns these rows)
for name, b in pairs({
	armt4zeus      = { hp = 420000, dps = 9500, speed = 38 },  -- front: Thor, chain lightning vs packs (EMP not counted)
	armt4atlas     = { hp = 480000, dps = 10000, speed = 34 }, -- front: Atlas, anchor, anti-big
	armt4peewee    = { hp = 360000, dps = 12000, speed = 58 }, -- front: Peewee Prime, brawler, army leader
	armt4aegis     = { hp = 260000, dps = 10000, speed = 72 }, -- center: Razor, assassin (plus its absorb shell)
	armt4prowler   = { hp = 330000, dps = 11000, speed = 52 }, -- center: Prowler, amphibious hunter
	armt4ratte     = { hp = 500000, dps = 9000, speed = 24 },  -- center: Ratte, siege landship
	armt4recluse   = { hp = 300000, dps = 9000, speed = 40 },  -- center: Recluse, zone control, all-terrain
	armt4olympus   = { hp = 220000, dps = 8000, speed = 30, alt = { shocker_high = true } }, -- back: artillery 3300+
	armt4starlight = { hp = 240000, dps = 8500, speed = 40 },  -- back: Starlight, tachyon sniper 2090
	armt4hive      = { hp = 280000, dps = 3000, speed = 34 },  -- back: Hive Mother, own laser only (drones: a1)
}) do
	T4.heroBalance[name] = b
end

-- v19 (dmgfix): a blast hits more units the bigger it is - against an army a 480-radius shell did 10.9x its shown
-- single-target DPS, a 130 one ~1x. The balance counts every weapon at its "army DPS": its DPS x
-- max(1, aoe / AOE_REF) ^ AOE_EXP, so the long-range splash heroes come out ~2-4x lower than v18 (Olympus /4,
-- Starfall /2, Armageddon /1.8) and their army damage is comparable to the front heroes'.
T4.AOE_REF = 150
T4.AOE_EXP = 1.2
function T4.armyFactor(wd)
	return math.max(1, (wd.areaofeffect or 0) / T4.AOE_REF) ^ T4.AOE_EXP
end

-- sustained DPS of a unitdef's real weapons, the weapondefs that count, and the army DPS (blast-weighted)
function T4.weaponDps(ud, alt)
	local total, counted, army = 0, {}, 0
	for _, w in ipairs(ud.weapons or {}) do
		local key = w.def and string.lower(w.def)
		local wd = key and ud.weapondefs and ud.weapondefs[key]
		local dmg = wd and wd.damage and wd.damage.default or 0
		if wd and not (alt and alt[key]) and wd.weapontype ~= "Shield" and not wd.paralyzer and (wd.range or 0) >= 150 and dmg > 1 then
			local dps = dmg * (wd.burst or 1) * (wd.projectiles or 1) / math.max(0.03, wd.reloadtime or 1)
			total = total + dps
			army = army + dps * T4.armyFactor(wd)
			counted[key] = wd
		end
	end
	return total, counted, army
end

local function balanceHero(ud)
	-- a unitdef table carries no name (it is the table key): the scaled model is Units/T4/<name>.s3o
	local name = (ud.objectname or ""):match("([%w_]+)%.s3o$") or ud.name
	local b = name and T4.heroBalance[name]
	if not b then
		return
	end
	local c = T4.HERO_COST
	ud.metalcost, ud.energycost, ud.buildtime = c.metal, c.energy, c.buildtime
	ud.mass = c.metal
	local alt = {}
	for key in pairs(b.alt or {}) do
		alt[#alt + 1] = key
	end
	ud.customparams.t4_alt_weapons = #alt > 0 and table.concat(alt, " ") or nil -- the hero gadget's DPS skips them
	ud.health = b.hp
	ud.speed = b.speed
	for fname, fd in pairs(ud.featuredefs or {}) do
		if fd.metal then
			fd.metal = math.floor(c.metal * (fname == "dead" and 0.55 or 0.22))
		end
	end
	local _, counted, army = T4.weaponDps(ud, b.alt)
	if army > 0 then
		local k = b.dps / army -- the target is the army DPS (blast-weighted), see T4.armyFactor
		-- the other arc of the same gun (b.alt) shoots with the same damage
		for key in pairs(b.alt or {}) do
			counted[key] = ud.weapondefs[key]
		end
		for _, wd in pairs(counted) do
			for armor, v in pairs(wd.damage) do
				wd.damage[armor] = v * k
			end
		end
	end
end

function T4.hero(ud, fx, extraWeapons)
	ud.maxthisunit = 1
	balanceHero(ud)
	local cp = ud.customparams
	cp.t4_hero = 1
	cp.t4_fx = fx
	-- v19: every hero takes EMP alike - half the paralysis damage (unit_paralyze_damage_multiplier.lua); api.stun lasts
	-- half as long on heroes (the base Juggernaut was immune, Bastion no longer is)
	cp.paralyzemultiplier = 0.5
	for _, wd in pairs(ud.weapondefs or {}) do
		scaleCegRefs(wd, fx)
	end
	if ud.sfxtypes and ud.sfxtypes.explosiongenerators then
		for i, ref in ipairs(ud.sfxtypes.explosiongenerators) do
			ud.sfxtypes.explosiongenerators[i] = FX.ref(ref, fx)
		end
	end
	-- v19: no visual step copies any more (the per-weapon trees are gone; the engine damage of a hero weapon is its
	-- base, the hero gadget applies ONE multiplier in UnitPreDamaged). The hero config (luarules/configs/heroes/*.lua)
	-- may add weapondefs (`weaponDefs`, spawned by the ability modules) and copies of its weapons (`weaponCopies`,
	-- swapped in by api.swapWeapons: a beam / lightning copy only draws - the engine dealt the shot's damage when it
	-- fired; a projectile copy keeps the damage of the weapon it copies).
	local H = heroConfig()
	local name = ud.objectname and ud.objectname:match("([^/]+)%.s3o$")
	local cfg = H and name and H.heroes[name]
	if cfg and cfg.weaponCopies then
		local copies = {}
		for suffix, c in pairs(cfg.weaponCopies) do
			for _, key in ipairs(c.keys or {}) do
				local wd = ud.weapondefs and ud.weapondefs[key]
				-- never a starburst (a respawned one never turns to its target) nor an unguided rocket with a trajectory
				-- height (a respawned one loses its target)
				if wd and wd.weapontype ~= "StarburstLauncher" and not (wd.weapontype == "MissileLauncher" and (wd.trajectoryheight or 0) > 0) then
					local w = deepcopy(wd)
					w.name = (wd.name or key) .. " (" .. suffix .. ")"
					for field, v in pairs(c.set or {}) do
						w[field] = deepcopy(v)
					end
					if w.weapontype == "LightningCannon" and c.set and c.set.rgbcolor then
						-- the GL4 lightning gadget (gfx_lightning_cannon_gl4.lua) reads these overrides
						local r, g, bl = tostring(c.set.rgbcolor):match("([%d%.]+)%s+([%d%.]+)%s+([%d%.]+)")
						w.customparams = w.customparams or {}
						w.customparams.lightning_color_r, w.customparams.lightning_color_g, w.customparams.lightning_color_b = r, g, bl
						w.customparams.lightning_core_color_r = "1"
						w.customparams.lightning_core_color_g = tostring(math.min(1, (tonumber(g) or 0) + 0.35))
						w.customparams.lightning_core_color_b = tostring(math.min(1, (tonumber(bl) or 0) + 0.25))
					end
					if w.weapontype == "BeamLaser" or w.weapontype == "LightningCannon" then
						w.damage = { default = 0 }
						w.beamtime = w.beamtime or 0.1
					end
					w.collidefriendly = false
					w.avoidfriendly = false
					w.customparams = w.customparams or {}
					w.customparams.t4_hero_weapon = 1
					w.customparams.t4_copy_of = key
					w.customparams.t4_copy = suffix
					w.customparams.spark_forkdamage = nil -- the lightning splash gadget would add its sparks twice
					copies[key .. "_" .. suffix] = w
				end
			end
		end
		for key, w in pairs(copies) do
			ud.weapondefs[key] = w
		end
	end
	if cfg and type(cfg.weaponDefs) == "function" then
		local ok, defs = pcall(cfg.weaponDefs, T4, ud)
		if ok and type(defs) == "table" then
			for key, wd in pairs(defs) do
				wd.customparams = wd.customparams or {}
				wd.customparams.t4_hero_weapon = 1
				ud.weapondefs[key] = wd
			end
		elseif not ok and Spring and Spring.Echo then
			Spring.Echo("[custom_t4] " .. tostring(name) .. ": weaponDefs failed: " .. tostring(defs))
		end
	end
	-- the ability kit's projectiles every hero shares (gamedata/custom_t4_abilities.lua)
	for key, wd in pairs(VFS.Include("gamedata/custom_t4_abilities.lua")(T4)) do
		ud.weapondefs[key] = ud.weapondefs[key] or wd
	end
	for key, wd in pairs(extraWeapons or {}) do
		wd.customparams = wd.customparams or {}
		wd.customparams.t4_hero_weapon = 1
		ud.weapondefs[key] = wd
	end
	return ud
end

local function setDamage(wd, dmg)
	wd.damage = { default = dmg }
	return wd
end

-- a copy of a weapondef with new damage (number or multiplier via mult), blast and effects
-- o = { damage, mult, aoe, ceg, cegtag, ... any weapondef field }
function T4.weaponFrom(wd, o)
	local w = deepcopy(wd)
	if o.mult and w.damage then
		for k, v in pairs(w.damage) do
			w.damage[k] = v * o.mult
		end
	end
	if o.damage then
		setDamage(w, o.damage)
	end
	if o.aoe then
		w.areaofeffect = o.aoe
		w.craterareaofeffect = o.aoe
		w.edgeeffectiveness = o.edge or 0.6
	end
	if o.ceg then
		w.explosiongenerator = o.ceg
	end
	if o.cegtag then
		w.cegtag = o.cegtag
	end
	for k, v in pairs(o) do
		if k ~= "mult" and k ~= "damage" and k ~= "aoe" and k ~= "ceg" and k ~= "cegtag" and k ~= "edge" then
			w[k] = deepcopy(v)
		end
	end
	-- hero warheads fly through their own army (they are spawned inside the hero)
	w.collidefriendly = false
	w.avoidfriendly = false
	w.stockpile = nil
	w.commandfire = nil
	w.metalpershot = nil
	w.energypershot = nil
	if w.customparams then
		w.customparams.nuclear = nil
		w.customparams.stockpilelimit = nil
	end
	return w
end

-- the Cortex tactical nuke (cortron) as a hero warhead: never intercepted, never stockpiled
local tacnuke
function T4.nukeWeapon(o)
	tacnuke = tacnuke or T4.base("units/CorBuildings/LandDefenceOffence/cortron.lua", "cortron").weapondefs.cortron_weapon
	local w = T4.weaponFrom(tacnuke, o)
	w.name = o.name or "Hero tactical warhead"
	w.targetable = 0
	w.interceptedbyshieldtype = 0
	w.reloadtime = 2
	return w
end

-- a homing missile warhead. Replaces starburst rockets too: a starburst spawned through
-- Spring.SpawnProjectile never turns to its target (it climbs until its ttl runs out), a homing missile
-- launched with the starburst's upward velocity curves over onto the target just the same.
function T4.missileWeapon(o)
	return {
		name = o.name or "Hero warhead",
		weapontype = "MissileLauncher",
		model = o.model or "cortronmissile.s3o",
		areaofeffect = o.aoe or 300,
		craterareaofeffect = o.aoe or 300,
		craterboost = 0.5,
		cratermult = 0.5,
		edgeeffectiveness = o.edge or 0.55,
		explosiongenerator = o.ceg,
		cegtag = o.cegtag or "cruisemissiletrail-tacnuke",
		flighttime = 12,
		impulsefactor = 0.8,
		noselfdamage = true,
		range = o.range or 2000,
		reloadtime = 5,
		smokecolor = 0.7,
		smokeperiod = 7,
		smokesize = 14,
		smoketime = 40,
		smoketrail = true,
		smoketrailcastshadow = false,
		soundhit = o.soundhit or "nukearm",
		soundhitwet = "nukewater",
		soundstart = o.soundstart or "mismed1",
		startvelocity = 200,
		texture1 = "null",
		texture2 = "smoketrailbar",
		tracks = true,
		turnrate = o.turnrate or 26000,
		turret = true,
		weaponacceleration = 260,
		weapontimer = 2,
		weaponvelocity = o.velocity or 900,
		avoidfeature = false,
		avoidfriendly = false,
		collidefriendly = false,
		collidefeature = false,
		targetable = 0,
		interceptedbyshieldtype = 0,
		damage = { default = o.damage or 1000 },
		customparams = {},
	}
end

-- a ballistic shell for meteors, nuclear shells and bomblets
function T4.shellWeapon(o)
	local w = {
		name = o.name or "Hero shell",
		weapontype = "Cannon",
		areaofeffect = o.aoe or 200,
		craterareaofeffect = o.aoe or 200,
		craterboost = 0.3,
		cratermult = 0.5,
		edgeeffectiveness = o.edge or 0.6,
		explosiongenerator = o.ceg or "custom:genericshellexplosion-huge",
		cegtag = o.cegtag,
		impulsefactor = 0.4,
		noselfdamage = true,
		range = o.range or 3000,
		reloadtime = 5,
		rgbcolor = o.rgb or "1 0.55 0.15",
		size = o.size or 6,
		separation = 0.45,
		nogap = false,
		stages = 12,
		sizedecay = -0.05,
		alphadecay = 0.25,
		soundhit = o.soundhit or "xplolrg4",
		soundhitwet = "splslrg",
		soundstart = o.soundstart,
		turret = true,
		weaponvelocity = o.velocity or 700,
		mygravity = o.gravity,
		avoidfeature = false,
		avoidfriendly = false,
		collidefriendly = false,
		damage = { default = o.damage or 1000 },
		customparams = {},
	}
	return w
end

-- an explosion-only weapon for Spring.SpawnExplosion (novas, flares)
function T4.novaWeapon(o)
	local w = T4.shellWeapon(o)
	w.name = o.name or "Hero nova"
	w.soundhit = o.soundhit or "nukearm"
	w.camerashake = o.aoe
	return w
end

-- the shield of the Armada/Cortex shield generators, resized for a mobile T4
function T4.shieldWeapon(radius, power, regen)
	return {
		avoidfeature = false,
		craterareaofeffect = 0,
		craterboost = 0,
		cratermult = 0,
		edgeeffectiveness = 0.15,
		name = "T4 Plasma Deflector",
		soundhitwet = "sizzle",
		weapontype = "Shield",
		shield = {
			alpha = 0.17,
			armortype = "shields",
			exterior = true,
			force = 2.5,
			intercepttype = 1,
			power = power,
			powerregen = regen,
			powerregenenergy = regen * 4,
			radius = radius,
			repulser = false,
			smart = true,
			startingpower = power * 0.5,
			visiblerepulse = true,
			badcolor = { 1, 0.2, 0.2, 0.2 },
			goodcolor = { 0.2, 1, 0.2, 0.17 },
		},
	}
end

-- T4 foundry: the faction's T3 gantry at 1.5x, much more build power
function T4.foundry(base, p)
	local ud = deepcopy(base)
	ud.objectname = "Units/T4/" .. p.name .. ".s3o"
	local value = p.value or 12
	local scale = p.scale or 1.5
	ud.metalcost = math.floor(ud.metalcost * value)
	ud.energycost = math.floor(ud.energycost * value)
	ud.buildtime = math.floor(ud.buildtime * value)
	ud.health = math.floor(ud.health * 8)
	ud.workertime = math.floor(ud.workertime * (p.workertime or 12))
	local fp = math.floor((ud.footprintx or 12) * scale + 0.5)
	ud.footprintx = fp
	ud.footprintz = fp
	-- first half solid, second half yard (open build/exit area), like the T3 gantries
	local rows = {}
	for r = 1, fp do
		rows[r] = string.rep(r <= math.floor(fp / 2) and "o" or "e", fp)
	end
	ud.yardmap = table.concat(rows, " ")
	ud.collisionvolumescales = scaleVec(ud.collisionvolumescales, scale)
	ud.collisionvolumeoffsets = scaleVec(ud.collisionvolumeoffsets, scale)
	ud.buildoptions = p.buildoptions
	ud.maxthisunit = 1 -- one hero altar per team: it builds and revives the four heroes of its side
	ud.explodeas = "korgExplosion"
	ud.selfdestructas = "korgExplosionSelfd"
	local cp = ud.customparams or {}
	ud.customparams = cp
	cp.techlevel = 4
	cp.t4_scale = scale
	cp.unitgroup = "buildert4"
	cp.subfolder = "T4"
	if cp.buildinggrounddecalsizex then
		cp.buildinggrounddecalsizex = cp.buildinggrounddecalsizex * scale
		cp.buildinggrounddecalsizey = cp.buildinggrounddecalsizey * scale
	end
	if ud.featuredefs then
		for fname, fd in pairs(ud.featuredefs) do
			if fd.metal then
				fd.metal = math.floor(ud.metalcost * (fname == "dead" and 0.55 or 0.22))
			end
			if fname == "dead" then
				fd.object = "Units/T4/" .. p.name .. "_dead.s3o"
				fd.collisionvolumescales = scaleVec(fd.collisionvolumescales, scale)
				fd.collisionvolumeoffsets = scaleVec(fd.collisionvolumeoffsets, scale)
				if fd.footprintx then
					fd.footprintx = math.floor(fd.footprintx * scale + 0.5)
					fd.footprintz = math.floor((fd.footprintz or fd.footprintx) * scale + 0.5)
				end
				mulField(fd, "height", scale)
			end
		end
	end
	return ud
end

return T4
