-- Custom T4 tier (denysfast/bar-game): builds T4 unitdefs from existing T2/T3 unitdefs.
-- Used from units/*/T4/*.lua via VFS.Include; lives outside units/ so the unitdef loader does not
-- try to load it as a unit. See CUSTOM.md, section "T4".
--
-- A T4 unit = the base unit's model scaled up (objects3d/Units/T4/<name>.s3o, generated by
-- tools/t4/build_models.py - the engine cannot scale models at runtime), its script, sounds and
-- weapons, with:
--   * cost, buildtime, health scaled by `value` (T4 is to T3 roughly what T3 is to T1)
--   * weapon damage scaled by `damage`, range by `range`, area of effect by `aoe`
--   * footprint / collision volume / movement class sized for the bigger model

local T4 = {}

local function deepcopy(v)
	if type(v) ~= "table" then
		return v
	end
	local out = {}
	for k, x in pairs(v) do
		out[k] = deepcopy(x)
	end
	return out
end
T4.deepcopy = deepcopy

local function scaleVec(str, mult)
	if type(str) ~= "string" then
		return str
	end
	local parts = {}
	for n in str:gmatch("%S+") do
		parts[#parts + 1] = string.format("%.1f", (tonumber(n) or 0) * mult)
	end
	return table.concat(parts, " ")
end
T4.scaleVec = scaleVec

local function mulField(t, key, mult)
	if t[key] then
		t[key] = t[key] * mult
	end
end

-- load one unitdef table from a unit file
function T4.base(path, name)
	local defs = VFS.Include(path)
	return deepcopy(defs[name])
end

-- scale one weapondef in place
-- opts: damage, range, aoe, velocity (default sqrt(range) so ballistic weapons still reach), size
function T4.scaleWeapon(wd, opts)
	local damage = opts.damage or 1
	local range = opts.range or 1
	if wd.damage then
		for armor, v in pairs(wd.damage) do
			wd.damage[armor] = v * damage
		end
	end
	if wd.range and wd.range > 0 then
		wd.range = wd.range * range
	end
	mulField(wd, "areaofeffect", opts.aoe or 1)
	mulField(wd, "craterareaofeffect", opts.aoe or 1)
	local vel = opts.velocity or math.sqrt(range)
	mulField(wd, "weaponvelocity", vel)
	mulField(wd, "startvelocity", vel)
	mulField(wd, "flighttime", range / vel)
	mulField(wd, "size", opts.size or 1)
	mulField(wd, "thickness", opts.size or 1)
	mulField(wd, "corethickness", opts.size or 1)
	mulField(wd, "camerashake", opts.aoe or 1)
	if wd.customparams and wd.customparams.overrange_distance then
		wd.customparams.overrange_distance = wd.customparams.overrange_distance * range
	end
	return wd
end

-- build a T4 unitdef
-- p = { value, health, damage, range, aoe, scale, speed, footprint, movementclass, metalcost,
--       weapons = { <key> = { damage=, range=, aoe=, velocity=, ... override fields } },
--       overrides = { field = value, customparams = {...} } }
function T4.derive(base, p)
	local ud = deepcopy(base)
	ud.objectname = "Units/T4/" .. p.name .. ".s3o"
	local value = p.value
	local scale = p.scale or 2

	ud.metalcost = p.metalcost or math.floor(ud.metalcost * value)
	ud.energycost = math.floor((ud.energycost or 0) * value)
	ud.buildtime = math.floor((ud.buildtime or 0) * value)
	ud.health = math.floor(ud.health * (p.health or value))
	ud.mass = ud.metalcost
	ud.speed = (ud.speed or 0) * (p.speed or 0.75)
	mulField(ud, "maxacc", p.accel or 0.6)
	mulField(ud, "maxdec", p.accel or 0.6)
	mulField(ud, "turnrate", p.turn or 0.55)
	mulField(ud, "turninplacespeedlimit", p.speed or 0.75)
	ud.sightdistance = math.floor((ud.sightdistance or 400) * (p.sight or 1.6))
	if ud.airsightdistance then
		ud.airsightdistance = math.floor(ud.airsightdistance * (p.sight or 1.6))
	end
	ud.footprintx = p.footprint
	ud.footprintz = p.footprint
	ud.movementclass = p.movementclass
	ud.maxslope = nil -- the movement class decides
	ud.maxwaterdepth = nil
	ud.collisionvolumescales = scaleVec(ud.collisionvolumescales, scale)
	ud.collisionvolumeoffsets = scaleVec(ud.collisionvolumeoffsets, scale)
	ud.cantbetransported = true
	ud.explodeas = p.explodeas or "korgExplosion"
	ud.selfdestructas = p.selfdestructas or "korgExplosionSelfd"
	ud.selfdestructcountdown = 10

	local cp = ud.customparams or {}
	ud.customparams = cp
	cp.techlevel = 4
	cp.t4_scale = scale
	cp.unitgroup = cp.unitgroup or "weapon"
	cp.subfolder = "T4"
	-- veterancy (unit_t4_abilities.lua): up to +50% damage and +25% range with experience
	cp.t4_xp_damage = p.xpDamage or 0.5
	cp.t4_xp_range = p.xpRange or 0.25
	cp.rangexpscale = nil -- the stock weapon-1 range bonus would stack on ours
	if cp.customrange then
		cp.customrange = cp.customrange * (p.range or 1)
	end

	-- wreck: the scaled wreck model, its metal follows the new cost
	if ud.featuredefs then
		for fname, fd in pairs(ud.featuredefs) do
			if fd.metal then
				fd.metal = math.floor(ud.metalcost * (fname == "dead" and 0.55 or 0.22))
			end
			if fname == "dead" then
				fd.object = "Units/T4/" .. p.name .. "_dead.s3o"
				fd.collisionvolumescales = scaleVec(fd.collisionvolumescales, scale)
				fd.collisionvolumeoffsets = scaleVec(fd.collisionvolumeoffsets, scale)
				if fd.footprintx then
					fd.footprintx = math.floor(fd.footprintx * scale + 0.5)
					fd.footprintz = math.floor((fd.footprintz or fd.footprintx) * scale + 0.5)
				end
				mulField(fd, "height", scale)
			end
			if fd.damage then
				fd.damage = math.floor(fd.damage * value)
			end
		end
	end

	-- weapons: global multipliers, then per-weapon overrides
	if ud.weapondefs then
		for key, wd in pairs(ud.weapondefs) do
			local w = p.weapons and p.weapons[key] or {}
			T4.scaleWeapon(wd, {
				damage = w.damage or p.damage or value,
				range = w.range or p.range or 1,
				aoe = w.aoe or p.aoe or 1.5,
				velocity = w.velocity,
				size = w.size or math.sqrt(scale),
			})
			for field, v in pairs(w) do
				if field ~= "damage" and field ~= "range" and field ~= "aoe" and field ~= "velocity" and field ~= "size" then
					wd[field] = deepcopy(v)
				end
			end
		end
	end

	if p.overrides then
		for field, v in pairs(p.overrides) do
			if field == "customparams" then
				for k, x in pairs(v) do
					cp[k] = x
				end
			else
				ud[field] = deepcopy(v)
			end
		end
	end
	return ud
end

-- the shield of the Armada/Cortex shield generators, resized for a mobile T4
function T4.shieldWeapon(radius, power, regen)
	return {
		avoidfeature = false,
		craterareaofeffect = 0,
		craterboost = 0,
		cratermult = 0,
		edgeeffectiveness = 0.15,
		name = "T4 Plasma Deflector",
		soundhitwet = "sizzle",
		weapontype = "Shield",
		shield = {
			alpha = 0.17,
			armortype = "shields",
			exterior = true,
			force = 2.5,
			intercepttype = 1,
			power = power,
			powerregen = regen,
			powerregenenergy = regen * 4,
			radius = radius,
			repulser = false,
			smart = true,
			startingpower = power * 0.5,
			visiblerepulse = true,
			badcolor = { 1, 0.2, 0.2, 0.2 },
			goodcolor = { 0.2, 1, 0.2, 0.17 },
		},
	}
end

-- T4 foundry: the faction's T3 gantry at 1.5x, much more build power
function T4.foundry(base, p)
	local ud = deepcopy(base)
	ud.objectname = "Units/T4/" .. p.name .. ".s3o"
	local value = p.value or 12
	local scale = p.scale or 1.5
	ud.metalcost = math.floor(ud.metalcost * value)
	ud.energycost = math.floor(ud.energycost * value)
	ud.buildtime = math.floor(ud.buildtime * value)
	ud.health = math.floor(ud.health * 8)
	ud.workertime = math.floor(ud.workertime * (p.workertime or 12))
	local fp = math.floor((ud.footprintx or 12) * scale + 0.5)
	ud.footprintx = fp
	ud.footprintz = fp
	-- first half solid, second half yard (open build/exit area), like the T3 gantries
	local rows = {}
	for r = 1, fp do
		rows[r] = string.rep(r <= math.floor(fp / 2) and "o" or "e", fp)
	end
	ud.yardmap = table.concat(rows, " ")
	ud.collisionvolumescales = scaleVec(ud.collisionvolumescales, scale)
	ud.collisionvolumeoffsets = scaleVec(ud.collisionvolumeoffsets, scale)
	ud.buildoptions = p.buildoptions
	ud.explodeas = "korgExplosion"
	ud.selfdestructas = "korgExplosionSelfd"
	local cp = ud.customparams or {}
	ud.customparams = cp
	cp.techlevel = 4
	cp.t4_scale = scale
	cp.unitgroup = "buildert4"
	cp.subfolder = "T4"
	if cp.buildinggrounddecalsizex then
		cp.buildinggrounddecalsizex = cp.buildinggrounddecalsizex * scale
		cp.buildinggrounddecalsizey = cp.buildinggrounddecalsizey * scale
	end
	if ud.featuredefs then
		for fname, fd in pairs(ud.featuredefs) do
			if fd.metal then
				fd.metal = math.floor(ud.metalcost * (fname == "dead" and 0.55 or 0.22))
			end
			if fname == "dead" then
				fd.object = "Units/T4/" .. p.name .. "_dead.s3o"
				fd.collisionvolumescales = scaleVec(fd.collisionvolumescales, scale)
				fd.collisionvolumeoffsets = scaleVec(fd.collisionvolumeoffsets, scale)
				if fd.footprintx then
					fd.footprintx = math.floor(fd.footprintx * scale + 0.5)
					fd.footprintz = math.floor((fd.footprintz or fd.footprintx) * scale + 0.5)
				end
				mulField(fd, "height", scale)
			end
		end
	end
	return ud
end

return T4
