-- AI army compositions, Armada (ai_doctrine.lua). Fast raids, rocket skirmish lines, Fatboy/Vanguard siege, hero-led T4 armies.
-- Unit counts are relative; the planner scales them to the budget. Factories named in desc.
return {
	t1 = {
		{
			id = "arm_t1_pawn_flood",
			name = "Pawn Flood",
			tactic = "raid",
			desc = "Bot lab only: mass Pawns with Ticks in front swarm expansions and mexes before defences go up.",
			units = {
				{ "armpw", 12 },
				{ "armflea", 4 },
			},
			min = 8,
			vs = { "eco", "light", "undefended" },
		},
		{
			id = "arm_t1_rocko_line",
			name = "Rocko Skirmish Line",
			tactic = "skirmish",
			desc = "Bot lab only: Rockos kite from range behind a Hammer/Warrior screen, Jethro for air.",
			units = {
				{ "armrock", 7, role = "skirm" },
				{ "armham", 4 },
				{ "armwar", 2 },
				{ "armjeth", 2 },
			},
			min = 8,
			vs = { "bots", "slow", "tanks" },
		},
		{
			id = "arm_t1_hammer_warrior_push",
			name = "Hammer/Warrior Push",
			tactic = "assault",
			desc = "Bot lab only: tanky Warriors lead, Hammers plasma the line, Pawns flank and finish.",
			units = {
				{ "armwar", 4 },
				{ "armham", 6 },
				{ "armpw", 5 },
				{ "armjeth", 1 },
			},
			min = 8,
			vs = { "bots", "light_defence" },
		},
		{
			id = "arm_t1_flash_raid",
			name = "Flash Raid",
			tactic = "raid",
			desc = "Vehicle plant only: fast Flash packs with Rover scouts hit the edges and run.",
			units = {
				{ "armflash", 10 },
				{ "armfav", 3 },
			},
			min = 6,
			vs = { "eco", "constructors", "artillery" },
		},
		{
			id = "arm_t1_stumpy_janus_wall",
			name = "Stumpy Wall with Janus",
			tactic = "assault",
			desc = "Vehicle plant only: a solid Stumpy front with Janus rockets behind and a Whistler for air.",
			units = {
				{ "armstump", 6 },
				{ "armjanus", 3, role = "skirm" },
				{ "armsam", 1 },
			},
			min = 6,
			vs = { "tanks", "bots", "light_defence" },
		},
		{
			id = "arm_t1_pincer_flank",
			name = "Pincer Amphibious Flank",
			tactic = "skirmish",
			desc = "Vehicle plant only: amphibious Pincers cross water and shores to flank, Stumpies hold the front.",
			units = {
				{ "armpincer", 6 },
				{ "armstump", 3 },
				{ "armsam", 1 },
			},
			min = 6,
			vs = { "water_maps", "bots" },
		},
		{
			id = "arm_t1_shellshock_siege",
			name = "Shellshocker Siege",
			tactic = "siege",
			desc = "Vehicle plant + bot lab: Shellshocker artillery shells defences behind Stumpies and Rockos.",
			units = {
				{ "armart", 5 },
				{ "armstump", 3 },
				{ "armrock", 3, role = "skirm" },
				{ "armjeth", 1 },
			},
			min = 7,
			vs = { "defences", "static", "turtle" },
		},
		{
			id = "arm_t1_combined_push",
			name = "Combined Arms Push",
			tactic = "assault",
			desc = "Bot lab + vehicle plant: Stumpies and Hammers front, Janus and Rockos behind, Jethro covers air.",
			units = {
				{ "armstump", 4 },
				{ "armham", 4 },
				{ "armrock", 3, role = "skirm" },
				{ "armjanus", 2, role = "skirm" },
				{ "armjeth", 1 },
			},
			min = 8,
			vs = { "mixed", "bots", "tanks" },
		},
		{
			id = "arm_t1_thunder_strike",
			name = "Thunder Strike",
			tactic = "air",
			desc = "Aircraft plant only: Thunder bombers with Falcon fighter escort and a Blink scout snipe eco.",
			units = {
				{ "armthund", 6 },
				{ "armfig", 4 },
				{ "armpeep", 1 },
			},
			min = 6,
			vs = { "eco", "static", "slow" },
		},
		{
			id = "arm_t1_hover_skirmish",
			name = "Hover Skirmish",
			tactic = "skirmish",
			desc = "Hover platform only: Skaters raid, Anacondas brawl, Possums rocket from range, one Swatter for air.",
			units = {
				{ "armsh", 6 },
				{ "armanac", 4 },
				{ "armmh", 2 },
				{ "armah", 1 },
			},
			min = 6,
			vs = { "water_maps", "light", "eco" },
		},
	},

	t2 = {
		{
			id = "arm_t2_sprinter_raid",
			name = "Sprinter Raid",
			tactic = "raid",
			desc = "Advanced bot lab only: fast Sprinters with EMP Webbers paralyse and shred outposts.",
			units = {
				{ "armfast", 10 },
				{ "armspid", 3 },
			},
			min = 8,
			vs = { "eco", "constructors", "light" },
		},
		{
			id = "arm_t2_recluse_skirmish",
			name = "Recluse Skirmish Web",
			tactic = "skirmish",
			desc = "Advanced bot lab only: all-terrain Recluse spiders and Fido kite from cliffs, Archangel and Compass support.",
			units = {
				{ "armsptk", 6, role = "skirm" },
				{ "armfido", 3, role = "skirm" },
				{ "armaak", 1 },
				{ "armmark", 1 },
			},
			min = 6,
			vs = { "bots", "slow", "hills" },
		},
		{
			id = "arm_t2_jaguar_raid",
			name = "Jaguar Lightning Raid",
			tactic = "raid",
			desc = "Advanced vehicle plant only: Jaguar lightning tanks with stealth Gremlins strike deep and fast.",
			units = {
				{ "armlatnk", 8 },
				{ "armgremlin", 3 },
			},
			min = 6,
			vs = { "eco", "light", "bots" },
		},
		{
			id = "arm_t2_bulldog_push",
			name = "Bulldog Armour Push",
			tactic = "assault",
			desc = "Advanced vehicle plant only: Bulldog heavy tanks with Jaguar flankers, Phalanx flak and a Seer radar.",
			units = {
				{ "armbull", 5 },
				{ "armlatnk", 3 },
				{ "armyork", 2 },
				{ "armseer", 1 },
			},
			min = 6,
			vs = { "tanks", "bots", "light_defence" },
		},
		{
			id = "arm_t2_zeus_assault",
			name = "Zeus Lightning Assault",
			tactic = "assault",
			desc = "Advanced bot lab + advanced vehicle plant: Zeus and Maverick brawl, Fido behind, Phalanx flak overhead.",
			units = {
				{ "armzeus", 6 },
				{ "armmav", 2 },
				{ "armfido", 3, role = "skirm" },
				{ "armyork", 2 },
				{ "armmark", 1 },
			},
			min = 8,
			vs = { "bots", "light_tanks", "swarms" },
		},
		{
			id = "arm_t2_fatboy_siege",
			name = "Fatboy Siege Line",
			tactic = "siege",
			desc = "Advanced bot lab + advanced vehicle plant: Fatboy plasma and Sharpshooters crack forts behind Zeus, jammed and flak-covered.",
			units = {
				{ "armfboy", 3 },
				{ "armsnipe", 2, role = "skirm" },
				{ "armzeus", 4 },
				{ "armyork", 1 },
				{ "armaser", 1 },
				{ "armmark", 1 },
			},
			min = 6,
			vs = { "defences", "turtle", "heavies" },
		},
		{
			id = "arm_t2_starlight_battery",
			name = "Starlight Battery",
			tactic = "siege",
			desc = "Advanced vehicle plant + advanced bot lab: Mauser and Ambassador artillery with Starlight snipers behind Bulldogs.",
			units = {
				{ "armmart", 5 },
				{ "armmerl", 2 },
				{ "armmanni", 2, role = "skirm" },
				{ "armbull", 3 },
				{ "armaak", 1 },
				{ "armjam", 1 },
				{ "armseer", 1 },
			},
			min = 7,
			vs = { "defences", "static", "slow" },
		},
		{
			id = "arm_t2_amphibious_landing",
			name = "Amphibious Landing",
			tactic = "assault",
			desc = "Advanced vehicle plant + advanced bot lab: Triton tanks and Pelican bots come out of the water on the flank.",
			units = {
				{ "armcroc", 4 },
				{ "armamph", 6 },
				{ "armyork", 1 },
			},
			min = 6,
			vs = { "water_maps", "shore_defences" },
		},
		{
			id = "arm_t2_brawler_gunships",
			name = "Brawler Gunship Wing",
			tactic = "air",
			desc = "Advanced aircraft plant only: Brawler gunships with Hawk fighter escort and a radar plane hunt ground armies.",
			units = {
				{ "armbrawl", 6 },
				{ "armhawk", 4 },
				{ "armawac", 1 },
			},
			min = 6,
			vs = { "ground", "no_aa", "artillery" },
		},
		{
			id = "arm_t2_phoenix_emp_strike",
			name = "Phoenix and Stiletto Strike",
			tactic = "air",
			desc = "Advanced aircraft plant only: Stiletto EMP bombers stun the target, Phoenix bombers level it, Hawks escort.",
			units = {
				{ "armpnix", 6 },
				{ "armstil", 2 },
				{ "armhawk", 5 },
			},
			min = 6,
			vs = { "eco", "static", "heavies" },
		},
	},

	t3 = {
		{
			id = "arm_t3_titan_spearhead",
			name = "Titan Spearhead",
			tactic = "assault",
			desc = "Gantry + advanced bot lab: Titans lead a Zeus mass, Phalanx and Archangel keep air off.",
			units = {
				{ "armbanth", 2 },
				{ "armzeus", 10 },
				{ "armyork", 2 },
				{ "armaak", 1 },
				{ "armmark", 1 },
			},
			min = 8,
			vs = { "heavies", "lines", "defences" },
		},
		{
			id = "arm_t3_razorback_wall",
			name = "Razorback Wall",
			tactic = "assault",
			desc = "Gantry + advanced vehicle plant: Razorbacks and Bulldogs grind forward as one armoured wall.",
			units = {
				{ "armraz", 6 },
				{ "armbull", 4 },
				{ "armyork", 2 },
				{ "armseer", 1 },
			},
			min = 6,
			vs = { "bots", "tanks", "mixed" },
		},
		{
			id = "arm_t3_marauder_raid",
			name = "Marauder Raid",
			tactic = "raid",
			desc = "Gantry + advanced vehicle plant: fast amphibious Marauders with Jaguars hit bases from water and flanks.",
			units = {
				{ "armmar", 8 },
				{ "armlatnk", 6 },
			},
			min = 6,
			vs = { "eco", "water_maps", "artillery" },
		},
		{
			id = "arm_t3_vanguard_siege",
			name = "Vanguard Siege",
			tactic = "siege",
			desc = "Gantry + advanced bot lab: Vanguard heavy artillery behind Razorbacks and Zeus, jammed and scouted.",
			units = {
				{ "armvang", 3 },
				{ "armraz", 3 },
				{ "armzeus", 6 },
				{ "armaak", 2 },
				{ "armaser", 1 },
				{ "armmark", 1 },
			},
			min = 8,
			vs = { "defences", "turtle", "static" },
		},
		{
			id = "arm_t3_thor_breakthrough",
			name = "Thor Breakthrough",
			tactic = "assault",
			desc = "Gantry + advanced vehicle plant: Thor walkers smash lines with Bulldogs, an Umbrella covers against nukes.",
			units = {
				{ "armthor", 2 },
				{ "armbull", 6 },
				{ "armyork", 2 },
				{ "armscab", 1, role = "support" },
			},
			min = 6,
			vs = { "heavies", "defences", "lines" },
		},
		{
			id = "arm_t3_lunkhead_flotilla",
			name = "Lunkhead Flotilla",
			tactic = "skirmish",
			desc = "Gantry + advanced vehicle plant: Lunkhead heavy hovers own water and shores, Marauders and Phalanx back them.",
			units = {
				{ "armlun", 6 },
				{ "armmar", 3 },
				{ "armyork", 2 },
			},
			min = 5,
			vs = { "water_maps", "ships", "shore_defences" },
		},
		{
			id = "arm_t3_titan_fatboy_line",
			name = "Titan and Fatboy Line",
			tactic = "siege",
			desc = "Gantry + advanced bot lab: slow unstoppable line of Titans, Fatboys and Sharpshooters under a jammer.",
			units = {
				{ "armbanth", 2 },
				{ "armfboy", 4 },
				{ "armsnipe", 3, role = "skirm" },
				{ "armaak", 2 },
				{ "armaser", 1 },
			},
			min = 6,
			vs = { "turtle", "heavies", "defences" },
		},
		{
			id = "arm_t3_razorback_recluse",
			name = "Razorback and Recluse Skirmish",
			tactic = "skirmish",
			desc = "Gantry + advanced bot lab: Razorbacks anchor, Recluse spiders and Sharpshooters pick off from range.",
			units = {
				{ "armraz", 3 },
				{ "armsptk", 8, role = "skirm" },
				{ "armsnipe", 3, role = "skirm" },
				{ "armaak", 1 },
				{ "armmark", 1 },
			},
			min = 8,
			vs = { "bots", "heavies", "slow" },
		},
		{
			id = "arm_t3_fortress_line",
			name = "Fortress Line",
			tactic = "defend",
			desc = "Gantry + advanced vehicle plant: Vanguards, a Thor and Starlights hold the key ground with flak and anti-nuke.",
			units = {
				{ "armvang", 2 },
				{ "armthor", 1 },
				{ "armmanni", 4, role = "skirm" },
				{ "armyork", 3 },
				{ "armscab", 1, role = "support" },
				{ "armseer", 1 },
			},
			min = 6,
			vs = { "assault", "experimentals", "air" },
		},
		{
			id = "arm_t3_liche_strike",
			name = "Liche Strike Wing",
			tactic = "air",
			desc = "Advanced aircraft plant (T3-tier strike): Liche atomic bombers and Blade gunships with Hawk escort delete key targets.",
			units = {
				{ "armliche", 3 },
				{ "armblade", 3 },
				{ "armhawk", 8 },
				{ "armawac", 1 },
			},
			min = 6,
			vs = { "experimentals", "eco", "static" },
		},
	},

	t4 = {
		{
			id = "arm_t4_atlas_hammer",
			name = "Atlas Hammer",
			tactic = "assault",
			desc = "Atlas anchors the front with Titans and Razorbacks, Zeus mass fills the gaps, flak overhead.",
			units = {
				{ "armt4atlas", 1, hero = true },
				{ "armbanth", 2 },
				{ "armraz", 4 },
				{ "armzeus", 10 },
				{ "armyork", 3 },
				{ "armmark", 1 },
			},
			min = 10,
			vs = { "lines", "heavies", "defences" },
		},
		{
			id = "arm_t4_atlas_armour",
			name = "Atlas Armoured Column",
			tactic = "assault",
			desc = "Atlas leads Thors and a Bulldog column straight through, Phalanx and Seer in tow.",
			units = {
				{ "armt4atlas", 1, hero = true },
				{ "armthor", 2 },
				{ "armbull", 8 },
				{ "armyork", 3 },
				{ "armseer", 1 },
			},
			min = 8,
			vs = { "tanks", "experimentals", "lines" },
		},
		{
			id = "arm_t4_atlas_bastion",
			name = "Atlas Bastion",
			tactic = "defend",
			desc = "Atlas holds the chokepoint with Vanguards and Starlights behind, Razorbacks as reserve, Umbrella against nukes.",
			units = {
				{ "armt4atlas", 1, hero = true },
				{ "armvang", 2 },
				{ "armmanni", 4, role = "skirm" },
				{ "armraz", 3 },
				{ "armaak", 3 },
				{ "armscab", 1, role = "support" },
			},
			min = 8,
			vs = { "assault", "experimentals" },
		},
		{
			id = "arm_t4_olympus_barrage",
			name = "Olympus Barrage",
			tactic = "siege",
			desc = "Olympus shells from the back; Razorbacks and Marauders screen, radar and jammers keep it seeing and hidden.",
			units = {
				{ "armt4olympus", 1, hero = true },
				{ "armraz", 6 },
				{ "armmar", 4 },
				{ "armmark", 2 },
				{ "armseer", 1 },
				{ "armjam", 2 },
				{ "armaak", 2 },
			},
			min = 10,
			vs = { "turtle", "defences", "static" },
		},
		{
			id = "arm_t4_olympus_grand_battery",
			name = "Olympus Grand Battery",
			tactic = "siege",
			desc = "Olympus plus Vanguards and Ambassadors form a long-range battery behind a Titan and Bulldog screen.",
			units = {
				{ "armt4olympus", 1, hero = true },
				{ "armvang", 3 },
				{ "armmerl", 3 },
				{ "armbanth", 1 },
				{ "armbull", 6 },
				{ "armyork", 2 },
				{ "armseer", 1 },
				{ "armjam", 1 },
			},
			min = 10,
			vs = { "fortress", "experimentals", "turtle" },
		},
		{
			id = "arm_t4_aegis_dome",
			name = "Aegis Dome Brawl",
			tactic = "assault",
			desc = "Aegis dome shields melee brawlers: Razorbacks, Marauders and Zeus close in under the deflector.",
			units = {
				{ "armt4aegis", 1, hero = true },
				{ "armraz", 5 },
				{ "armmar", 6 },
				{ "armzeus", 8 },
				{ "armaak", 2 },
			},
			min = 10,
			vs = { "artillery", "lines", "heavies" },
		},
		{
			id = "arm_t4_aegis_sniper_nest",
			name = "Aegis Sniper Nest",
			tactic = "skirmish",
			desc = "Aegis dome protects fragile long-range Sharpshooters and Fatboys while Zeus guard the edge.",
			units = {
				{ "armt4aegis", 1, hero = true },
				{ "armsnipe", 6, role = "skirm" },
				{ "armfboy", 3 },
				{ "armzeus", 6 },
				{ "armaak", 2 },
				{ "armmark", 1 },
			},
			min = 10,
			vs = { "heavies", "experimentals", "artillery" },
		},
		{
			id = "arm_t4_aegis_titan_wall",
			name = "Aegis Titan Wall",
			tactic = "assault",
			desc = "Aegis shield over Titans with Marauder and Jaguar brawlers pushing into the enemy core.",
			units = {
				{ "armt4aegis", 1, hero = true },
				{ "armbanth", 2 },
				{ "armmar", 6 },
				{ "armlatnk", 8 },
				{ "armyork", 2 },
			},
			min = 10,
			vs = { "defences", "lines", "air" },
		},
		{
			id = "arm_t4_zeus_storm",
			name = "Zeus Storm",
			tactic = "assault",
			desc = "Hero Zeus leads an all-lightning army: Zeus bots, Jaguars and Webber EMP spiders chain-stun the enemy.",
			units = {
				{ "armt4zeus", 1, hero = true },
				{ "armzeus", 12 },
				{ "armlatnk", 8 },
				{ "armspid", 4 },
				{ "armaak", 2 },
			},
			min = 12,
			vs = { "swarms", "bots", "experimentals" },
		},
		{
			id = "arm_t4_zeus_emp_blitz",
			name = "Zeus EMP Blitz",
			tactic = "raid",
			desc = "Hero Zeus with Stiletto EMP bombers and Webbers: paralyse the base, Marauders and Sprinters finish it.",
			units = {
				{ "armt4zeus", 1, hero = true },
				{ "armstil", 4 },
				{ "armhawk", 4 },
				{ "armspid", 6 },
				{ "armmar", 6 },
				{ "armfast", 6 },
			},
			min = 12,
			vs = { "eco", "static", "experimentals" },
		},
	},
}
