-- AI army compositions, Legion (ai_doctrine.lua). Heat rays, napalm, rails and salvo rockets; T4 armies built around the Legion heroes.
-- Needs modoption experimentallegionfaction=1. Unit names verified against the Legion factory buildoptions
-- (leglab legvp legap leghp / legalab legavp legaap / leggant / legt4gant).
return {
	t1 = {
		{
			id = "leg_t1_goblin_swarm",
			name = "Goblin Swarm",
			tactic = "raid",
			desc = "Bot lab only. A cloud of 30-metal Goblins backed by Phobos assault bots floods mex lines and outnumbers early scouts.",
			units = {
				{ "leggob", 16 },
				{ "legcen", 3 },
			},
			min = 10,
			vs = { "eco", "light", "early" },
		},
		{
			id = "leg_t1_karkinos_line",
			name = "Karkinos Line",
			tactic = "assault",
			desc = "Bot lab only. Tanky Karkinos infantry lead a Satyr plasma wall, Ballistas behind, Toxotai against early air.",
			units = {
				{ "legkark", 5 },
				{ "leglob", 8 },
				{ "legbal", 3 },
				{ "legaabot", 2 },
			},
			min = 8,
			vs = { "bots", "light" },
		},
		{
			id = "leg_t1_ballista_skirmish",
			name = "Ballista Skirmish",
			tactic = "skirmish",
			desc = "Bot lab only. Ballista rockets out-range T1 front units while Satyrs and a few Karkinos hold the gap.",
			units = {
				{ "legbal", 8 },
				{ "leglob", 5 },
				{ "legkark", 2 },
			},
			min = 7,
			vs = { "bots", "static" },
		},
		{
			id = "leg_t1_alaris_raid",
			name = "Alaris Raid",
			tactic = "raid",
			desc = "Vehicle plant only. Fast Alaris assault tanks with Wheelie scouts hit constructors and undefended expansions.",
			units = {
				{ "leghades", 12 },
				{ "legscout", 3 },
			},
			min = 8,
			vs = { "eco", "light" },
		},
		{
			id = "leg_t1_decurion_push",
			name = "Decurion Push",
			tactic = "assault",
			desc = "Vehicle plant only. Armored Decurions soak the front, Helios skirmishers and Alaris flank the line.",
			units = {
				{ "leggat", 5 },
				{ "leghelios", 4 },
				{ "leghades", 4 },
			},
			min = 7,
			vs = { "vehicles", "bots" },
		},
		{
			id = "leg_t1_barrage_park",
			name = "Barrage Park",
			tactic = "siege",
			desc = "Vehicle plant + bot lab. Napalm Barrages and Lance railguns shell defences while Ballistas and Karkinos screen.",
			units = {
				{ "legbar", 3 },
				{ "legrail", 3, role = "skirm" },
				{ "legbal", 4 },
				{ "legkark", 2 },
			},
			min = 6,
			vs = { "static", "turtle" },
		},
		{
			id = "leg_t1_mosquito_swarm",
			name = "Mosquito Swarm",
			tactic = "air",
			desc = "Aircraft plant. Mosquito gunships with stockpiled rockets hunt raiders and constructors, Noctua fighters as escort.",
			units = {
				{ "legmos", 8 },
				{ "legfig", 4 },
			},
			min = 6,
			vs = { "eco", "light", "no_aa" },
		},
		{
			id = "leg_t1_martyr_strike",
			name = "Martyr Strike",
			tactic = "air",
			desc = "Aircraft plant. Martyr suicide drones dive into clumped armies and mex fields; Blindfold strips radar/mines, Noctua escort.",
			units = {
				{ "legkam", 8 },
				{ "legcib", 1 },
				{ "legfig", 4 },
			},
			min = 6,
			vs = { "clumps", "eco" },
		},
		{
			id = "leg_t1_cardea_tide",
			name = "Cardea Tide",
			tactic = "assault",
			desc = "Hover platform only. Shotgun Cardeas and Nereus hovertanks cross water and plains, Glaucus flank, Salacia rockets and Alpheus AA behind.",
			units = {
				{ "legcar", 3 },
				{ "legner", 4 },
				{ "legsh", 6 },
				{ "legmh", 2 },
				{ "legah", 1 },
			},
			min = 7,
			vs = { "water_maps", "vehicles" },
		},
		{
			id = "leg_t1_combined_cohort",
			name = "Combined Cohort",
			tactic = "assault",
			desc = "Bot lab + vehicle plant. Decurions and Karkinos as the armored front, Satyr mass, Barrage napalm and Toxotai AA.",
			units = {
				{ "leggat", 3 },
				{ "legkark", 3 },
				{ "leglob", 6 },
				{ "legbar", 2 },
				{ "legaabot", 2 },
			},
			min = 8,
			vs = { "mixed", "bots", "air" },
		},
	},

	t2 = {
		{
			id = "leg_t2_hoplite_raid",
			name = "Hoplite Raid",
			tactic = "raid",
			desc = "Advanced bot lab only. Fast Hoplites and all-terrain Infestors cut into T2 eco from unexpected angles.",
			units = {
				{ "legstr", 10 },
				{ "leginfestor", 4 },
			},
			min = 8,
			vs = { "eco", "light" },
		},
		{
			id = "leg_t2_phalanx_wall",
			name = "Phalanx Wall",
			tactic = "assault",
			desc = "Advanced bot lab only. Shielded Phalanx riot bots in front, Belcher napalm and Arquebus rails behind, Aquilon AA, radar + jammer.",
			units = {
				{ "legshot", 6 },
				{ "legbart", 4 },
				{ "legsrail", 3, role = "skirm" },
				{ "legadvaabot", 2, role = "aa" },
				{ "legaradk", 1 },
				{ "legajamk", 1 },
			},
			min = 8,
			vs = { "bots", "raiders", "swarm" },
		},
		{
			id = "leg_t2_rocket_rain",
			name = "Rocket Rain",
			tactic = "siege",
			desc = "Advanced bot lab + advanced vehicle plant. Thanatos salvos and stealthy Boreas launchers with Mantis drones pound defences behind Phalanx; Charon AA, Pheme radar for range.",
			units = {
				{ "leghrk", 4 },
				{ "legavroc", 2 },
				{ "legvcarry", 2, role = "skirm" },
				{ "legshot", 3 },
				{ "legvflak", 2 },
				{ "legavrad", 1 },
			},
			min = 7,
			vs = { "static", "turtle" },
		},
		{
			id = "leg_t2_amphibious_assault",
			name = "Tide Breakers",
			tactic = "assault",
			desc = "Advanced bot lab only. Amphibious Telchines and Snapper screwdrive bombs attack from water and shore, Infestors climb the cliffs, Aquilon AA.",
			units = {
				{ "legamph", 6 },
				{ "legsnapper", 8 },
				{ "leginfestor", 4 },
				{ "legadvaabot", 2, role = "aa" },
			},
			min = 8,
			vs = { "water_maps", "navy", "coast" },
		},
		{
			id = "leg_t2_quickshot_raid",
			name = "Quickshot Raid",
			tactic = "raid",
			desc = "Advanced vehicle plant only. Burst-fire Quickshots run down constructors and artillery; two Charons keep gunships off.",
			units = {
				{ "legmrv", 12 },
				{ "legvflak", 2 },
			},
			min = 8,
			vs = { "eco", "artillery", "light" },
		},
		{
			id = "leg_t2_prometheus_push",
			name = "Prometheus Push",
			tactic = "assault",
			desc = "Advanced vehicle plant only. Prometheus heat-ray tanks melt the front, Gladiator skirmishers behind, Charon AA, radar + jammer trucks.",
			units = {
				{ "legaheattank", 4 },
				{ "legaskirmtank", 5 },
				{ "legvflak", 2 },
				{ "legavrad", 1 },
				{ "legavjam", 1 },
			},
			min = 7,
			vs = { "heavy", "vehicles", "bots" },
		},
		{
			id = "leg_t2_inferno_battery",
			name = "Inferno Battery",
			tactic = "siege",
			desc = "Advanced vehicle plant only. Inferno napalm, Medusa salvo rockets and Cleaver cluster shells break fortified lines, Gladiators screen.",
			units = {
				{ "leginf", 2 },
				{ "legmed", 2 },
				{ "legamcluster", 3 },
				{ "legaskirmtank", 4 },
				{ "legvflak", 2 },
				{ "legavrad", 1 },
			},
			min = 7,
			vs = { "static", "turtle", "clumps" },
		},
		{
			id = "leg_t2_phoenix_run",
			name = "Phoenix Run",
			tactic = "air",
			desc = "Advanced aircraft plant. Phoenix heat-ray bombers burn a path through armies and eco; Ajax and Venator fighters clear the sky.",
			units = {
				{ "legphoenix", 8 },
				{ "legafigdef", 4 },
				{ "legvenator", 4 },
			},
			min = 8,
			vs = { "eco", "heavy", "no_aa" },
		},
		{
			id = "leg_t2_tyrannus_armada",
			name = "Tyrannus Armada",
			tactic = "air",
			desc = "Advanced aircraft plant. A Tyrannus flying fortress with Stronghold gunships as a slow air battlegroup, Ajax/Venator escort vs fighters.",
			units = {
				{ "legfort", 1 },
				{ "legstronghold", 3 },
				{ "legafigdef", 4 },
				{ "legvenator", 3 },
			},
			min = 4,
			vs = { "ground", "static", "no_aa" },
		},
		{
			id = "leg_t2_incinerator_grind",
			name = "Incinerator Grind",
			tactic = "assault",
			desc = "Advanced bot lab + advanced vehicle plant. Two Incinerator heat rays and Prometheus tanks grind forward behind Phalanx shields; Belchers, Charon AA, jammer.",
			units = {
				{ "leginc", 2 },
				{ "legaheattank", 3 },
				{ "legshot", 4 },
				{ "legbart", 3 },
				{ "legvflak", 2 },
				{ "legajamk", 1 },
			},
			min = 7,
			vs = { "heavy", "static", "bots" },
		},
	},

	t3 = {
		{
			id = "leg_t3_sol_invictus_vanguard",
			name = "Sol Invictus Vanguard",
			tactic = "assault",
			desc = "Gantry + T2 labs. One Sol Invictus heat-ray mech leads a Phalanx riot escort; Aquilon and Charon keep bombers off it.",
			units = {
				{ "legeheatraymech", 1 },
				{ "legshot", 6 },
				{ "legadvaabot", 3, role = "aa" },
				{ "legvflak", 2 },
				{ "legavrad", 1 },
			},
			min = 6,
			vs = { "heavy", "swarm", "static" },
		},
		{
			id = "leg_t3_astraeus_bombardment",
			name = "Astraeus Bombardment",
			tactic = "siege",
			desc = "Gantry + advanced vehicle plant. Two Astraeus cluster-plasma mechs shell bases from extreme range; Keres and Gladiators hold the screen, radar + jammer.",
			units = {
				{ "legelrpcmech", 2 },
				{ "legkeres", 2 },
				{ "legaskirmtank", 6 },
				{ "legvflak", 3 },
				{ "legavrad", 1 },
				{ "legavjam", 1 },
			},
			min = 6,
			vs = { "static", "turtle", "experimentals" },
		},
		{
			id = "leg_t3_daedalus_battery",
			name = "Daedalus Rail Battery",
			tactic = "skirmish",
			desc = "Gantry + advanced bot lab. Daedalus rail accelerators and Arquebus rails pick off heavies at range behind Phalanx shields.",
			units = {
				{ "legerailtank", 3, role = "skirm" },
				{ "legsrail", 6, role = "skirm" },
				{ "legshot", 4 },
				{ "legadvaabot", 2, role = "aa" },
			},
			min = 6,
			vs = { "experimentals", "heavy" },
		},
		{
			id = "leg_t3_praetorian_assault",
			name = "Praetorian Assault",
			tactic = "assault",
			desc = "Gantry + advanced vehicle plant. Fast Praetorian shotgun mechs and Keres tanks crash the line, Prometheus heat rays follow up.",
			units = {
				{ "legeshotgunmech", 3 },
				{ "legkeres", 2 },
				{ "legaheattank", 4 },
				{ "legvflak", 2 },
			},
			min = 5,
			vs = { "heavy", "bots", "vehicles" },
		},
		{
			id = "leg_t3_javelin_raid",
			name = "Javelin Raid",
			tactic = "raid",
			desc = "Gantry + advanced vehicle plant. Amphibious Javelin raiders with Quickshots strike T2 eco and artillery across land and water.",
			units = {
				{ "legjav", 8 },
				{ "legmrv", 8 },
				{ "legvflak", 2 },
			},
			min = 8,
			vs = { "eco", "artillery", "water_maps" },
		},
		{
			id = "leg_t3_charybdis_tide",
			name = "Charybdis Tide",
			tactic = "assault",
			desc = "Gantry only (+ Charon). A pack of Charybdis heavy hovertanks with Javelins sweeps shores and flat maps faster than walkers can answer.",
			units = {
				{ "legehovertank", 8 },
				{ "legjav", 4 },
				{ "legvflak", 2 },
			},
			min = 6,
			vs = { "water_maps", "vehicles", "navy" },
		},
		{
			id = "leg_t3_myrmidon_swarm",
			name = "Myrmidon Swarm",
			tactic = "skirmish",
			desc = "Gantry + advanced bot lab. All-terrain Myrmidon drone carriers with Infestors and Arquebus rails walk over cliffs where tanks can't follow.",
			units = {
				{ "legeallterrainmech", 4, role = "skirm" },
				{ "leginfestor", 8 },
				{ "legsrail", 4, role = "skirm" },
				{ "legadvaabot", 2, role = "aa" },
			},
			min = 8,
			vs = { "hills", "static", "bots" },
		},
		{
			id = "leg_t3_keres_bulwark",
			name = "Keres Bulwark",
			tactic = "defend",
			desc = "Gantry + T2 labs. Anti-swarm Keres tanks and Phalanx shields hold a front; Aquilon AA, radar/jammer and a Hera anti-nuke travel with it.",
			units = {
				{ "legkeres", 4 },
				{ "legshot", 6 },
				{ "legadvaabot", 3, role = "aa" },
				{ "legaradk", 1 },
				{ "legajamk", 1 },
				{ "legavantinuke", 1, role = "support" },
			},
			min = 6,
			vs = { "swarm", "raiders", "nukes" },
		},
		{
			id = "leg_t3_praetorian_phoenix",
			name = "Fire from Above",
			tactic = "assault",
			desc = "Gantry + advanced aircraft plant. Praetorians pin the enemy army while Phoenix heat-ray bombers burn it; Ajax fighters and Charon AA cover.",
			units = {
				{ "legeshotgunmech", 2 },
				{ "legphoenix", 6 },
				{ "legafigdef", 4 },
				{ "legvflak", 2 },
			},
			min = 6,
			vs = { "heavy", "clumps" },
		},
		{
			id = "leg_t3_grand_legion",
			name = "Grand Legion",
			tactic = "assault",
			desc = "Gantry + all T2 labs. Sol Invictus and a Daedalus anchor a full combined-arms army: Keres, Charybdis, Phalanx, Gladiators, AA, radar, jammer, anti-nuke.",
			units = {
				{ "legeheatraymech", 1 },
				{ "legerailtank", 1, role = "skirm" },
				{ "legkeres", 2 },
				{ "legehovertank", 4 },
				{ "legshot", 4 },
				{ "legaskirmtank", 4 },
				{ "legvflak", 3 },
				{ "legavrad", 1 },
				{ "legavjam", 1 },
				{ "legavantinuke", 1, role = "support" },
			},
			min = 10,
			vs = { "mixed", "experimentals" },
		},
	},

	t4 = {
		-- Helios, the Sunbringer: twin heat rays, a brawler that wants company in the melee
		{
			id = "leg_t4_sunbringer_vanguard",
			name = "Sunbringer Vanguard",
			tactic = "assault",
			desc = "Helios walks beside a Sol Invictus; Keres and Phalanx absorb fire around the two heat-ray giants, heavy AA against bombers.",
			units = {
				{ "legt4helios", 1, hero = true },
				{ "legeheatraymech", 1 },
				{ "legkeres", 3 },
				{ "legshot", 8 },
				{ "legadvaabot", 4, role = "aa" },
				{ "legvflak", 3 },
			},
			min = 10,
			vs = { "heavy", "swarm", "static" },
		},
		{
			id = "leg_t4_solar_crusade",
			name = "Solar Crusade",
			tactic = "assault",
			desc = "Helios leads an all-heat-ray column: Praetorians, Prometheus tanks and Incinerators burn everything in reach; Charon AA, jammer hides the approach.",
			units = {
				{ "legt4helios", 1, hero = true },
				{ "legeshotgunmech", 2 },
				{ "legaheattank", 6 },
				{ "leginc", 2 },
				{ "legvflak", 3 },
				{ "legavjam", 1 },
			},
			min = 8,
			vs = { "heavy", "experimentals" },
		},
		{
			id = "leg_t4_helios_bastion",
			name = "Helios Bastion",
			tactic = "defend",
			desc = "Helios holds the key front with Keres anti-swarm tanks, Myrmidon drone carriers and Phalanx; Hera anti-nuke and radar ride along.",
			units = {
				{ "legt4helios", 1, hero = true },
				{ "legkeres", 3 },
				{ "legeallterrainmech", 2, role = "skirm" },
				{ "legshot", 6 },
				{ "legadvaabot", 4, role = "aa" },
				{ "legavantinuke", 1, role = "support" },
				{ "legavrad", 1 },
			},
			min = 10,
			vs = { "swarm", "raiders", "nukes" },
		},
		-- Starfall, the Astronomer: plasma from ~7000 elmos; needs vision and a solid screen
		{
			id = "leg_t4_orbital_siege",
			name = "Orbital Siege",
			tactic = "siege",
			desc = "Starfall and an Astraeus bombard from beyond any turret; Keres and Phalanx screen, radar gives the range, jammer hides the guns.",
			units = {
				{ "legt4starfall", 1, hero = true },
				{ "legelrpcmech", 1 },
				{ "legkeres", 3 },
				{ "legshot", 8 },
				{ "legvflak", 4 },
				{ "legavrad", 1 },
				{ "legavjam", 1 },
			},
			min = 10,
			vs = { "static", "turtle", "experimentals" },
		},
		{
			id = "leg_t4_starfall_observatory",
			name = "Starfall Observatory",
			tactic = "siege",
			desc = "Starfall with a long-range park: Inferno napalm, Medusa salvos and Daedalus rails kill what gets close; double radar, anti-nuke, flak.",
			units = {
				{ "legt4starfall", 1, hero = true },
				{ "leginf", 3 },
				{ "legmed", 3 },
				{ "legerailtank", 2, role = "skirm" },
				{ "legvflak", 3 },
				{ "legavrad", 2 },
				{ "legavantinuke", 1, role = "support" },
			},
			min = 8,
			vs = { "static", "clumps", "heavy" },
		},
		-- Longinus, the Spear: the titan hunter rail tank
		{
			id = "leg_t4_titan_hunt",
			name = "Titan Hunt",
			tactic = "skirmish",
			desc = "Longinus with Daedalus and Arquebus rails: a rail line that deletes enemy experimentals and heroes at range; Phalanx and Aquilon cover.",
			units = {
				{ "legt4longinus", 1, hero = true },
				{ "legerailtank", 2, role = "skirm" },
				{ "legsrail", 8, role = "skirm" },
				{ "legshot", 4 },
				{ "legadvaabot", 3, role = "aa" },
			},
			min = 10,
			vs = { "experimentals", "heroes", "heavy" },
		},
		{
			id = "leg_t4_spear_phalanx",
			name = "Spear Phalanx",
			tactic = "assault",
			desc = "Longinus spearheads a fast armored thrust: Keres, Charybdis hovertanks and Gladiators keep pace with it; Charon AA and a jammer truck.",
			units = {
				{ "legt4longinus", 1, hero = true },
				{ "legkeres", 3 },
				{ "legehovertank", 6 },
				{ "legaskirmtank", 6 },
				{ "legvflak", 3 },
				{ "legavjam", 1 },
			},
			min = 10,
			vs = { "vehicles", "heavy", "experimentals" },
		},
		-- Tempest, the Stormblade: fast melee blademaster, wants fast company
		{
			id = "leg_t4_stormblade_raid",
			name = "Stormblade Raid",
			tactic = "raid",
			desc = "Tempest leads the fastest Legion units: Javelins, Quickshots and Hoplites dive the enemy eco and artillery behind the blademaster.",
			units = {
				{ "legt4tempest", 1, hero = true },
				{ "legjav", 6 },
				{ "legmrv", 10 },
				{ "legstr", 8 },
				{ "legvflak", 2 },
			},
			min = 12,
			vs = { "eco", "artillery", "light" },
		},
		{
			id = "leg_t4_storm_tide",
			name = "Storm Tide",
			tactic = "assault",
			desc = "Tempest with Praetorian shotgun mechs and a Charybdis hover pack: a close-range shock army that crosses water and closes distance fast.",
			units = {
				{ "legt4tempest", 1, hero = true },
				{ "legeshotgunmech", 2 },
				{ "legehovertank", 8 },
				{ "legvflak", 3 },
			},
			min = 8,
			vs = { "heavy", "artillery", "water_maps" },
		},
		{
			id = "leg_t4_all_terrain_blitz",
			name = "All-Terrain Blitz",
			tactic = "raid",
			desc = "Tempest with Myrmidon carriers, Infestor spiders and Snapper bombs: comes over cliffs and from water where nobody built defences.",
			units = {
				{ "legt4tempest", 1, hero = true },
				{ "legeallterrainmech", 3, role = "skirm" },
				{ "leginfestor", 10 },
				{ "legsnapper", 8 },
				{ "legadvaabot", 2, role = "aa" },
			},
			min = 12,
			vs = { "hills", "eco", "static" },
		},
	},
}
