-- AI army compositions, Cortex (ai_doctrine.lua). Armoured brawlers, rocket skirmish and heavy artillery, T1..T4.
return {
	t1 = {
		{
			id = "cor_t1_grunt_swarm",
			name = "Grunt Swarm",
			tactic = "raid",
			desc = "Bot lab only. A mass of cheap Grunts floods expansions and mex lines, a few Aggravators crack the first towers.",
			units = {
				{ "corak", 14 },
				{ "corstorm", 2, role = "skirm" },
			},
			min = 10,
			vs = { "eco", "light", "artillery" },
		},
		{
			id = "cor_t1_thug_line",
			name = "Thug Line",
			tactic = "assault",
			desc = "Bot lab only. Tanky Thugs walk in front, Aggravators fire over them, Trashers keep bombers off, a Graverobber repairs and reclaims.",
			units = {
				{ "corthud", 8 },
				{ "corstorm", 4, role = "skirm" },
				{ "corcrash", 2 },
				{ "cornecro", 1 },
			},
			min = 8,
			vs = { "bots", "light" },
		},
		{
			id = "cor_t1_aggravator_siege",
			name = "Aggravator Rocket Siege",
			tactic = "siege",
			desc = "Bot lab only. Massed Aggravator rockets outrange light defences; Thugs and Grunts screen the rocket line.",
			units = {
				{ "corstorm", 8, role = "skirm" },
				{ "corthud", 3 },
				{ "corak", 3 },
			},
			min = 8,
			vs = { "defences", "static" },
		},
		{
			id = "cor_t1_incisor_raid",
			name = "Incisor Raid",
			tactic = "raid",
			desc = "Vehicle plant only. Fast Incisors with Rascal scouts hit undefended mexes and constructors, then run.",
			units = {
				{ "corgator", 8 },
				{ "corfav", 4 },
			},
			min = 6,
			vs = { "eco", "constructors", "light" },
		},
		{
			id = "cor_t1_brute_push",
			name = "Brute Push",
			tactic = "assault",
			desc = "Vehicle plant only. Brute tanks lead, Pounders clear bot swarms, Lashers and Wolverines hit from behind.",
			units = {
				{ "corraid", 6 },
				{ "corlevlr", 2 },
				{ "cormist", 2, role = "skirm" },
				{ "corwolv", 2 },
			},
			min = 6,
			vs = { "vehicles", "bots" },
		},
		{
			id = "cor_t1_wolverine_battery",
			name = "Wolverine Battery",
			tactic = "siege",
			desc = "Vehicle plant + bot lab. Wolverine artillery shells a defended front while a Thug and Aggravator wall holds it.",
			units = {
				{ "corwolv", 5 },
				{ "corthud", 5 },
				{ "corstorm", 2, role = "skirm" },
			},
			min = 8,
			vs = { "defences", "static", "slow" },
		},
		{
			id = "cor_t1_pounder_bulwark",
			name = "Pounder Bulwark",
			tactic = "defend",
			desc = "Vehicle plant + bot lab. Anti-swarm Pounders and Thugs hold a choke against bot rushes; Trashers cover the sky.",
			units = {
				{ "corlevlr", 5 },
				{ "corthud", 4 },
				{ "corcrash", 2 },
			},
			min = 6,
			vs = { "bots", "swarm", "raiders" },
		},
		{
			id = "cor_t1_whirlwind_strike",
			name = "Whirlwind Strike",
			tactic = "air",
			desc = "Aircraft plant. Whirlwind bombers carpet eco and artillery, Valiant fighters clear the way, a Fink spots targets.",
			units = {
				{ "corshad", 6 },
				{ "corveng", 4 },
				{ "corfink", 1 },
			},
			min = 6,
			vs = { "eco", "artillery", "static" },
		},
		{
			id = "cor_t1_shuriken_swarm",
			name = "Shuriken Swarm",
			tactic = "air",
			desc = "Aircraft plant. Paralyzer drones stun raiders and tanks in the open while Valiants escort against enemy fighters.",
			units = {
				{ "corbw", 10 },
				{ "corveng", 4 },
			},
			min = 8,
			vs = { "vehicles", "raiders", "constructors" },
		},
		{
			id = "cor_t1_goon_hover_raid",
			name = "Goon Hover Raid",
			tactic = "raid",
			desc = "Hover platform only. Goons and Caymans raid along shores and water, Mangonel rockets and a Halberd back them, a Birdeater guards the air.",
			units = {
				{ "corsh", 6 },
				{ "corsnap", 4 },
				{ "cormh", 2 },
				{ "corhal", 1 },
				{ "corah", 1 },
			},
			min = 6,
			vs = { "eco", "naval", "light" },
		},
	},

	t2 = {
		{
			id = "cor_t2_mammoth_wall",
			name = "Mammoth Wall",
			tactic = "assault",
			desc = "Advanced bot lab only. Mammoths and Sumos soak damage, Sheldon mortars lob behind, Manticores and a Deceiver jammer cover.",
			units = {
				{ "corsumo", 2 },
				{ "corcan", 4 },
				{ "cormort", 4 },
				{ "coraak", 2 },
				{ "corspec", 1 },
			},
			min = 6,
			vs = { "bots", "vehicles", "defences" },
		},
		{
			id = "cor_t2_fiend_raid",
			name = "Fiend Raid",
			tactic = "raid",
			desc = "Advanced bot lab only. Fast flamethrower Fiends burn eco and bot swarms; Bedbug crawling bombs are thrown into clumps.",
			units = {
				{ "corpyro", 10 },
				{ "corroach", 4 },
			},
			min = 8,
			vs = { "eco", "light", "bots", "swarm" },
		},
		{
			id = "cor_t2_arbiter_line",
			name = "Arbiter Rocket Line",
			tactic = "skirmish",
			desc = "Advanced bot lab only. Heavy rocket Arbiters kite at range behind Sumos; an Augur radar gives them the range, Manticores the sky.",
			units = {
				{ "corhrk", 6, role = "skirm" },
				{ "corcan", 3 },
				{ "coraak", 2 },
				{ "corvoyr", 1 },
			},
			min = 6,
			vs = { "vehicles", "heavy", "slow" },
		},
		{
			id = "cor_t2_termite_climb",
			name = "Termite Climb",
			tactic = "assault",
			desc = "Advanced bot lab only. All-terrain Termite spiders cross cliffs and hills to hit from unexpected angles, Arbiters follow.",
			units = {
				{ "cortermite", 5 },
				{ "corhrk", 3, role = "skirm" },
				{ "coraak", 1 },
			},
			min = 5,
			vs = { "vehicles", "defences", "hills" },
		},
		{
			id = "cor_t2_amphibious_assault",
			name = "Poison Arrow Tide",
			tactic = "assault",
			desc = "Advanced vehicle plant only. Amphibious Poison Arrows and Salamanders cross rivers and lakes and land behind defences; Fury flak escorts.",
			units = {
				{ "corparrow", 3 },
				{ "corsala", 5 },
				{ "corsent", 2 },
			},
			min = 5,
			vs = { "naval", "vehicles", "water_maps" },
		},
		{
			id = "cor_t2_quaker_siege",
			name = "Quaker Siege Park",
			tactic = "siege",
			desc = "Advanced vehicle plant only. Tremor and Quaker artillery with Negotiator rockets flatten defence lines; Tigers screen, Omen radar and Obscurer jammer support.",
			units = {
				{ "cortrem", 2 },
				{ "cormart", 4 },
				{ "corvroc", 2 },
				{ "correap", 3 },
				{ "corsent", 1 },
				{ "corvrad", 1 },
				{ "coreter", 1 },
			},
			min = 6,
			vs = { "defences", "static", "slow" },
		},
		{
			id = "cor_t2_tzar_breakthrough",
			name = "Tzar Breakthrough",
			tactic = "assault",
			desc = "Advanced vehicle plant + advanced bot lab. Tzar heavy tanks and Sumos smash a hole, Sheldon mortars and Fury flak follow, a Deceiver hides them.",
			units = {
				{ "corgol", 3 },
				{ "corcan", 4 },
				{ "cormort", 3 },
				{ "corsent", 2 },
				{ "corspec", 1 },
			},
			min = 6,
			vs = { "heavy", "defences", "vehicles" },
		},
		{
			id = "cor_t2_banisher_skirmish",
			name = "Banisher Missile Screen",
			tactic = "skirmish",
			desc = "Advanced vehicle plant + advanced bot lab. Banisher and Arbiter missiles out-range heavy tanks from behind a Sumo screen; Fury and Deceiver support.",
			units = {
				{ "corban", 3, role = "skirm" },
				{ "corhrk", 4, role = "skirm" },
				{ "corcan", 3 },
				{ "corsent", 1 },
				{ "corspec", 1 },
			},
			min = 6,
			vs = { "heavy", "vehicles", "experimentals" },
		},
		{
			id = "cor_t2_hailstorm_raid",
			name = "Hailstorm Strike",
			tactic = "air",
			desc = "Advanced aircraft plant. Hailstorm heavy bombers level eco and artillery parks, Nighthawk fighters escort, a radar plane spots.",
			units = {
				{ "corhurc", 5 },
				{ "corvamp", 4 },
				{ "corawac", 1 },
			},
			min = 5,
			vs = { "eco", "artillery", "static", "slow" },
		},
		{
			id = "cor_t2_wasp_pack",
			name = "Wasp Pack",
			tactic = "air",
			desc = "Advanced aircraft plant. Wasp gunships hunt ground armies, a Dragon flying fortress anchors the pack, Nighthawks keep enemy fighters off.",
			units = {
				{ "corape", 8 },
				{ "corvamp", 3 },
				{ "corcrwh", 1 },
			},
			min = 6,
			vs = { "vehicles", "bots", "no_aa" },
		},
	},

	t3 = {
		{
			id = "cor_t3_juggernaut_march",
			name = "Juggernaut March",
			tactic = "assault",
			desc = "Gantry + advanced bot lab. The Juggernaut leads a Sumo phalanx straight through the front; Manticores and a Deceiver cover it.",
			units = {
				{ "corkorg", 1 },
				{ "corcan", 6 },
				{ "coraak", 3 },
				{ "corspec", 1 },
			},
			min = 5,
			vs = { "heavy", "defences", "bots" },
		},
		{
			id = "cor_t3_karganeth_pack",
			name = "Karganeth Pack",
			tactic = "assault",
			desc = "Gantry + advanced bot lab. All-terrain Karganeth mechs and Termites climb over terrain and swarm defences from the flanks.",
			units = {
				{ "corkarg", 6 },
				{ "cortermite", 4 },
				{ "coraak", 2 },
			},
			min = 5,
			vs = { "defences", "vehicles", "hills" },
		},
		{
			id = "cor_t3_catapult_barrage",
			name = "Catapult Barrage",
			tactic = "siege",
			desc = "Gantry + advanced bot lab. Catapult heavy rockets and Arbiters rain on the enemy base from range; Karganeths hold the front, an Augur spots.",
			units = {
				{ "corcat", 4 },
				{ "corhrk", 4, role = "skirm" },
				{ "corkarg", 3 },
				{ "coraak", 2 },
				{ "corvoyr", 1 },
			},
			min = 6,
			vs = { "defences", "static", "slow" },
		},
		{
			id = "cor_t3_shiva_landing",
			name = "Shiva Landing",
			tactic = "assault",
			desc = "Gantry + advanced vehicle plant. Amphibious Shiva siege mechs and Poison Arrows walk through water to strike coastlines; Fury flak escorts.",
			units = {
				{ "corshiva", 6 },
				{ "corparrow", 3 },
				{ "corsent", 2 },
			},
			min = 5,
			vs = { "naval", "defences", "water_maps" },
		},
		{
			id = "cor_t3_behemoth_fortress",
			name = "Behemoth Fortress",
			tactic = "defend",
			desc = "Gantry + advanced vehicle plant. A Behemoth heavy turret anchors a hold point with Tigers, Tremor artillery, Fury flak and a mobile anti-nuke.",
			units = {
				{ "corjugg", 1 },
				{ "correap", 4 },
				{ "cortrem", 2 },
				{ "corsent", 2 },
				{ "cormabm", 1 },
			},
			min = 4,
			vs = { "experimentals", "heavy", "nukes" },
		},
		{
			id = "cor_t3_demon_inferno",
			name = "Demon Inferno",
			tactic = "assault",
			desc = "Gantry + advanced bot lab. Demon flamethrower mechs and a Fiend horde burn through bot swarms and bases; Sumos tank, Manticores guard.",
			units = {
				{ "cordemon", 3 },
				{ "corpyro", 8 },
				{ "corcan", 3 },
				{ "coraak", 2 },
			},
			min = 6,
			vs = { "bots", "swarm", "light", "bases" },
		},
		{
			id = "cor_t3_cataphract_strike",
			name = "Cataphract Strike",
			tactic = "raid",
			desc = "Gantry only (+ advanced vehicle plant for flak). Fast Cataphract laser hovertanks strike eco and outposts on land and water.",
			units = {
				{ "corsok", 8 },
				{ "corsent", 2 },
			},
			min = 4,
			vs = { "eco", "naval", "vehicles" },
		},
		{
			id = "cor_t3_dragon_armada",
			name = "Dragon Armada",
			tactic = "air",
			desc = "Advanced aircraft plant, late game. Dragon flying fortresses lead Wasp gunships and Hailstorm bombers; Nighthawks win the sky.",
			units = {
				{ "corcrwh", 2 },
				{ "corape", 6 },
				{ "corhurc", 4 },
				{ "corvamp", 6 },
			},
			min = 8,
			vs = { "ground", "eco", "no_aa" },
		},
		{
			id = "cor_t3_shiva_combined",
			name = "Shiva Combined Arms",
			tactic = "skirmish",
			desc = "Gantry + advanced vehicle plant. Shivas and Cataphracts trade at range behind a Tiger screen; Fury flak and an Obscurer jammer support.",
			units = {
				{ "corshiva", 4 },
				{ "corsok", 4 },
				{ "correap", 4 },
				{ "corsent", 2 },
				{ "coreter", 1 },
			},
			min = 6,
			vs = { "heavy", "vehicles", "mixed" },
		},
		{
			id = "cor_t3_skuttle_ambush",
			name = "Skuttle Ambush",
			tactic = "raid",
			desc = "Gantry + advanced bot lab. Karganeths draw fire while Skuttle crawling bombs dive into enemy experimentals and clumped heavies.",
			units = {
				{ "corkarg", 4 },
				{ "corsktl", 6 },
				{ "coraak", 2 },
			},
			min = 6,
			vs = { "experimentals", "heavy", "clumps" },
		},
	},

	t4 = {
		{
			id = "cor_t4_colossus_warband",
			name = "Colossus Warband",
			tactic = "assault",
			desc = "Colossus leads from the front with Command Aura; a Juggernaut, Karganeths and a Sumo phalanx march in its aura, Manticores cover.",
			units = {
				{ "cort4colossus", 1, hero = true },
				{ "corkorg", 1 },
				{ "corkarg", 4 },
				{ "corcan", 6 },
				{ "coraak", 3 },
			},
			min = 8,
			vs = { "heavy", "experimentals", "bots" },
		},
		{
			id = "cor_t4_colossus_iron_legion",
			name = "Colossus Iron Legion",
			tactic = "assault",
			desc = "Colossus with a heavy armour column: a Behemoth, Tzars and Tigers; War Stomp breaks the line, Fury flak and an Obscurer support.",
			units = {
				{ "cort4colossus", 1, hero = true },
				{ "corjugg", 1 },
				{ "corgol", 4 },
				{ "correap", 6 },
				{ "corsent", 3 },
				{ "coreter", 1 },
			},
			min = 8,
			vs = { "vehicles", "defences", "heavy" },
		},
		{
			id = "cor_t4_colossus_vanguard",
			name = "Colossus Vanguard",
			tactic = "skirmish",
			desc = "Colossus tanks the fire while Catapults and Shivas punish anything that engages it; Manticores keep bombers off.",
			units = {
				{ "cort4colossus", 1, hero = true },
				{ "corcat", 3 },
				{ "corshiva", 4 },
				{ "coraak", 3 },
			},
			min = 6,
			vs = { "experimentals", "heavy", "mixed" },
		},
		{
			id = "cor_t4_bastion_siege_protocol",
			name = "Bastion Siege Protocol",
			tactic = "siege",
			desc = "Bastion enters Siege Protocol at the enemy wall; Catapults, Tremors and Quakers shell behind its armour, Omen radar spots.",
			units = {
				{ "cort4bastion", 1, hero = true },
				{ "corcat", 4 },
				{ "cortrem", 4 },
				{ "cormart", 6 },
				{ "corsent", 3 },
				{ "corvrad", 1 },
			},
			min = 8,
			vs = { "defences", "static", "bases" },
		},
		{
			id = "cor_t4_bastion_citadel",
			name = "Bastion Citadel",
			tactic = "defend",
			desc = "Bastion's Citadel dome shelters a rocket and Shiva firebase; a Behemoth anchors it and a mobile anti-nuke covers the hold point.",
			units = {
				{ "cort4bastion", 1, hero = true },
				{ "corjugg", 1 },
				{ "corhrk", 8, role = "skirm" },
				{ "corshiva", 3 },
				{ "coraak", 4 },
				{ "cormabm", 1 },
			},
			min = 8,
			vs = { "experimentals", "air", "nukes" },
		},
		{
			id = "cor_t4_armageddon_rocket_rain",
			name = "Armageddon Rocket Rain",
			tactic = "siege",
			desc = "Armageddon's long rockets plus Catapults and Arbiters bury the enemy at extreme range; Karganeths screen the front, an Augur spots.",
			units = {
				{ "cort4armageddon", 1, hero = true },
				{ "corcat", 4 },
				{ "corhrk", 6, role = "skirm" },
				{ "corkarg", 4 },
				{ "coraak", 3 },
				{ "corvoyr", 1 },
			},
			min = 8,
			vs = { "defences", "static", "slow", "clumps" },
		},
		{
			id = "cor_t4_armageddon_long_watch",
			name = "Armageddon Long Watch",
			tactic = "skirmish",
			desc = "Armageddon stays back while Cataphracts screen and Banishers and Tremors add range; Salvage Nanites keep the line alive, Obscurer hides it.",
			units = {
				{ "cort4armageddon", 1, hero = true },
				{ "corsok", 6 },
				{ "corban", 4, role = "skirm" },
				{ "cortrem", 2 },
				{ "corsent", 3 },
				{ "coreter", 1 },
			},
			min = 8,
			vs = { "heavy", "vehicles", "experimentals" },
		},
		{
			id = "cor_t4_hellwalker_inferno",
			name = "Hellwalker Inferno",
			tactic = "assault",
			desc = "Hellwalker Immolation plus Demons and a Fiend horde: a wall of fire that erases swarms and bases; Manticores guard the sky.",
			units = {
				{ "cort4hellwalker", 1, hero = true },
				{ "cordemon", 4 },
				{ "corpyro", 10 },
				{ "coraak", 2 },
			},
			min = 8,
			vs = { "bots", "swarm", "bases" },
		},
		{
			id = "cor_t4_hellwalker_hellcharge",
			name = "Hellwalker Hellcharge",
			tactic = "raid",
			desc = "Fast Hellwalker Hellcharges into the enemy rear with Cataphracts and Karganeths; Skuttles finish the experimentals it pins.",
			units = {
				{ "cort4hellwalker", 1, hero = true },
				{ "corsok", 6 },
				{ "corkarg", 4 },
				{ "corsktl", 6 },
			},
			min = 8,
			vs = { "eco", "experimentals", "artillery" },
		},
		{
			id = "cor_t4_hellwalker_brawl",
			name = "Hellwalker Brawl",
			tactic = "assault",
			desc = "Hellwalker and a Juggernaut brawl at close range with Demons, Sumos and Mammoths soaking fire; Fury flak covers.",
			units = {
				{ "cort4hellwalker", 1, hero = true },
				{ "corkorg", 1 },
				{ "cordemon", 2 },
				{ "corcan", 6 },
				{ "corsumo", 2 },
				{ "corsent", 2 },
			},
			min = 8,
			vs = { "heavy", "experimentals", "bots" },
		},
	},
}
